// @ts-nocheck
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class ForwardSpec {
    /**
     * Creates a new ForwardSpec instance.
     * @param {Partial<ForwardSpec>} [$$source = {}] - The source object to create the ForwardSpec.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("contextName" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["contextName"] = "";
        }
        if (!("namespace" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["namespace"] = "";
        }
        if (!("targetKind" in $$source)) {
            /**
             * @member
             * @type {TargetKind}
             */
            this["targetKind"] = TargetKind.$zero;
        }
        if (!("targetName" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["targetName"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["targetGVR"] = undefined;
        }
        if (!("localPort" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["localPort"] = 0;
        }
        if (!("remotePort" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["remotePort"] = 0;
        }
        if (!("status" in $$source)) {
            /**
             * @member
             * @type {ForwardStatus}
             */
            this["status"] = ForwardStatus.$zero;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["podName"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["error"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ForwardSpec instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ForwardSpec}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ForwardSpec(/** @type {Partial<ForwardSpec>} */($$parsedSource));
    }
}

/**
 * @readonly
 * @enum {string}
 */
export const ForwardStatus = {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero: "",

    StatusActive: "active",
    StatusReconnecting: "reconnecting",
    StatusFailed: "failed",
    StatusStopped: "stopped",
};

export class Manager {
    /**
     * Creates a new Manager instance.
     * @param {Partial<Manager>} [$$source = {}] - The source object to create the Manager.
     */
    constructor($$source = {}) {

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Manager instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Manager}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Manager(/** @type {Partial<Manager>} */($$parsedSource));
    }
}

/**
 * @readonly
 * @enum {string}
 */
export const TargetKind = {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero: "",

    TargetKindPod: "pod",
    TargetKindStatefulPod: "statefulpod",
    TargetKindSelector: "selector",
};
