// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class Session {
    "connectedClusters": string[];
    "lastActiveContext"?: string;
    "activeNamespaces": { [_ in string]?: string };
    "openTabs": TabState[];
    "activeTab": number;
    "sidebarCollapsed": boolean;
    "terminalFontSize": number;
    "sidebarWidth"?: number;
    "window": WindowState;

    /** Creates a new Session instance. */
    constructor($$source: Partial<Session> = {}) {
        if (!("connectedClusters" in $$source)) {
            this["connectedClusters"] = [];
        }
        if (!("activeNamespaces" in $$source)) {
            this["activeNamespaces"] = {};
        }
        if (!("openTabs" in $$source)) {
            this["openTabs"] = [];
        }
        if (!("activeTab" in $$source)) {
            this["activeTab"] = 0;
        }
        if (!("sidebarCollapsed" in $$source)) {
            this["sidebarCollapsed"] = false;
        }
        if (!("terminalFontSize" in $$source)) {
            this["terminalFontSize"] = 0;
        }
        if (!("window" in $$source)) {
            this["window"] = (new WindowState());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Session instance from a string or object.
     */
    static createFrom($$source: any = {}): Session {
        const $$createField0_0 = $$createType0;
        const $$createField2_0 = $$createType1;
        const $$createField3_0 = $$createType3;
        const $$createField8_0 = $$createType4;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("connectedClusters" in $$parsedSource) {
            $$parsedSource["connectedClusters"] = $$createField0_0($$parsedSource["connectedClusters"]);
        }
        if ("activeNamespaces" in $$parsedSource) {
            $$parsedSource["activeNamespaces"] = $$createField2_0($$parsedSource["activeNamespaces"]);
        }
        if ("openTabs" in $$parsedSource) {
            $$parsedSource["openTabs"] = $$createField3_0($$parsedSource["openTabs"]);
        }
        if ("window" in $$parsedSource) {
            $$parsedSource["window"] = $$createField8_0($$parsedSource["window"]);
        }
        return new Session($$parsedSource as Partial<Session>);
    }
}

export class TabState {
    "clusterContext": string;
    "gvr": string;
    "namespace": string;
    "name": string;
    "scrollPosition"?: number;

    /** Creates a new TabState instance. */
    constructor($$source: Partial<TabState> = {}) {
        if (!("clusterContext" in $$source)) {
            this["clusterContext"] = "";
        }
        if (!("gvr" in $$source)) {
            this["gvr"] = "";
        }
        if (!("namespace" in $$source)) {
            this["namespace"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TabState instance from a string or object.
     */
    static createFrom($$source: any = {}): TabState {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new TabState($$parsedSource as Partial<TabState>);
    }
}

export class WindowState {
    "x": number;
    "y": number;
    "width": number;
    "height": number;

    /** Creates a new WindowState instance. */
    constructor($$source: Partial<WindowState> = {}) {
        if (!("x" in $$source)) {
            this["x"] = 0;
        }
        if (!("y" in $$source)) {
            this["y"] = 0;
        }
        if (!("width" in $$source)) {
            this["width"] = 0;
        }
        if (!("height" in $$source)) {
            this["height"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new WindowState instance from a string or object.
     */
    static createFrom($$source: any = {}): WindowState {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new WindowState($$parsedSource as Partial<WindowState>);
    }
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
const $$createType1 = $Create.Map($Create.Any, $Create.Any);
const $$createType2 = TabState.createFrom;
const $$createType3 = $Create.Array($$createType2);
const $$createType4 = WindowState.createFrom;
