// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as time$0 from "../../../../../time/models.js";

/**
 * APIResource describes a discoverable resource on the cluster, including
 * optional metadata useful for rendering (printer columns, subresources,
 * scale subresource paths for CRDs).
 */
export class APIResource {
    "gvr": string;
    "kind": string;
    "namespaced": boolean;
    "subresources": ResourceSubresources;
    "printerColumns"?: AdditionalPrinterColumn[];
    "scaleSpec"?: ScaleSubresourceSpec | null;

    /** Creates a new APIResource instance. */
    constructor($$source: Partial<APIResource> = {}) {
        if (!("gvr" in $$source)) {
            this["gvr"] = "";
        }
        if (!("kind" in $$source)) {
            this["kind"] = "";
        }
        if (!("namespaced" in $$source)) {
            this["namespaced"] = false;
        }
        if (!("subresources" in $$source)) {
            this["subresources"] = (new ResourceSubresources());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new APIResource instance from a string or object.
     */
    static createFrom($$source: any = {}): APIResource {
        const $$createField3_0 = $$createType0;
        const $$createField4_0 = $$createType2;
        const $$createField5_0 = $$createType4;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("subresources" in $$parsedSource) {
            $$parsedSource["subresources"] = $$createField3_0($$parsedSource["subresources"]);
        }
        if ("printerColumns" in $$parsedSource) {
            $$parsedSource["printerColumns"] = $$createField4_0($$parsedSource["printerColumns"]);
        }
        if ("scaleSpec" in $$parsedSource) {
            $$parsedSource["scaleSpec"] = $$createField5_0($$parsedSource["scaleSpec"]);
        }
        return new APIResource($$parsedSource as Partial<APIResource>);
    }
}

export class APIServerHealth {
    "livez": HealthStatus;
    "readyz": HealthStatus;
    "healthz": HealthStatus;

    /** Creates a new APIServerHealth instance. */
    constructor($$source: Partial<APIServerHealth> = {}) {
        if (!("livez" in $$source)) {
            this["livez"] = HealthStatus.$zero;
        }
        if (!("readyz" in $$source)) {
            this["readyz"] = HealthStatus.$zero;
        }
        if (!("healthz" in $$source)) {
            this["healthz"] = HealthStatus.$zero;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new APIServerHealth instance from a string or object.
     */
    static createFrom($$source: any = {}): APIServerHealth {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new APIServerHealth($$parsedSource as Partial<APIServerHealth>);
    }
}

/**
 * AdditionalPrinterColumn mirrors the CRD printer column definition used by
 * kubectl's column rendering.
 */
export class AdditionalPrinterColumn {
    "name": string;

    /**
     * "string" | "integer" | "number" | "boolean" | "date"
     */
    "type": string;
    "format"?: string;
    "description"?: string;

    /**
     * 0 = visible by default
     */
    "priority": number;
    "jsonPath": string;

    /** Creates a new AdditionalPrinterColumn instance. */
    constructor($$source: Partial<AdditionalPrinterColumn> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("type" in $$source)) {
            this["type"] = "";
        }
        if (!("priority" in $$source)) {
            this["priority"] = 0;
        }
        if (!("jsonPath" in $$source)) {
            this["jsonPath"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AdditionalPrinterColumn instance from a string or object.
     */
    static createFrom($$source: any = {}): AdditionalPrinterColumn {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new AdditionalPrinterColumn($$parsedSource as Partial<AdditionalPrinterColumn>);
    }
}

export class ClusterHealth {
    "apiServer": APIServerHealth;
    "components": ComponentHealth[];
    "nodes": NodeSummary;
    "checkedAt": time$0.Time;

    /** Creates a new ClusterHealth instance. */
    constructor($$source: Partial<ClusterHealth> = {}) {
        if (!("apiServer" in $$source)) {
            this["apiServer"] = (new APIServerHealth());
        }
        if (!("components" in $$source)) {
            this["components"] = [];
        }
        if (!("nodes" in $$source)) {
            this["nodes"] = (new NodeSummary());
        }
        if (!("checkedAt" in $$source)) {
            this["checkedAt"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ClusterHealth instance from a string or object.
     */
    static createFrom($$source: any = {}): ClusterHealth {
        const $$createField0_0 = $$createType5;
        const $$createField1_0 = $$createType7;
        const $$createField2_0 = $$createType8;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("apiServer" in $$parsedSource) {
            $$parsedSource["apiServer"] = $$createField0_0($$parsedSource["apiServer"]);
        }
        if ("components" in $$parsedSource) {
            $$parsedSource["components"] = $$createField1_0($$parsedSource["components"]);
        }
        if ("nodes" in $$parsedSource) {
            $$parsedSource["nodes"] = $$createField2_0($$parsedSource["nodes"]);
        }
        return new ClusterHealth($$parsedSource as Partial<ClusterHealth>);
    }
}

export class ComponentHealth {
    "name": string;
    "status": HealthStatus;
    "message": string;

    /** Creates a new ComponentHealth instance. */
    constructor($$source: Partial<ComponentHealth> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("status" in $$source)) {
            this["status"] = HealthStatus.$zero;
        }
        if (!("message" in $$source)) {
            this["message"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ComponentHealth instance from a string or object.
     */
    static createFrom($$source: any = {}): ComponentHealth {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ComponentHealth($$parsedSource as Partial<ComponentHealth>);
    }
}

export enum ConnectionStatus {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = 0,

    StatusDisconnected = 0,
    StatusConnecting = 1,
    StatusConnected = 2,
    StatusError = 3,
};

export enum HealthStatus {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = 0,

    HealthOK = 0,
    HealthDegraded = 1,
    HealthUnknown = 2,
};

export class KubeContext {
    "name": string;
    "cluster": string;
    "user": string;
    "namespace": string;
    "status": ConnectionStatus;
    "serverVersion": string;
    "provider": string;
    "sourcePath": string;
    "isDefault": boolean;

    /** Creates a new KubeContext instance. */
    constructor($$source: Partial<KubeContext> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("cluster" in $$source)) {
            this["cluster"] = "";
        }
        if (!("user" in $$source)) {
            this["user"] = "";
        }
        if (!("namespace" in $$source)) {
            this["namespace"] = "";
        }
        if (!("status" in $$source)) {
            this["status"] = ConnectionStatus.$zero;
        }
        if (!("serverVersion" in $$source)) {
            this["serverVersion"] = "";
        }
        if (!("provider" in $$source)) {
            this["provider"] = "";
        }
        if (!("sourcePath" in $$source)) {
            this["sourcePath"] = "";
        }
        if (!("isDefault" in $$source)) {
            this["isDefault"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new KubeContext instance from a string or object.
     */
    static createFrom($$source: any = {}): KubeContext {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new KubeContext($$parsedSource as Partial<KubeContext>);
    }
}

export class Manager {

    /** Creates a new Manager instance. */
    constructor($$source: Partial<Manager> = {}) {

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Manager instance from a string or object.
     */
    static createFrom($$source: any = {}): Manager {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Manager($$parsedSource as Partial<Manager>);
    }
}

export class NodeSummary {
    "total": number;
    "ready": number;
    "notReady": number;
    "schedulingDisabled": number;
    "permissionDenied": boolean;

    /** Creates a new NodeSummary instance. */
    constructor($$source: Partial<NodeSummary> = {}) {
        if (!("total" in $$source)) {
            this["total"] = 0;
        }
        if (!("ready" in $$source)) {
            this["ready"] = 0;
        }
        if (!("notReady" in $$source)) {
            this["notReady"] = 0;
        }
        if (!("schedulingDisabled" in $$source)) {
            this["schedulingDisabled"] = 0;
        }
        if (!("permissionDenied" in $$source)) {
            this["permissionDenied"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new NodeSummary instance from a string or object.
     */
    static createFrom($$source: any = {}): NodeSummary {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new NodeSummary($$parsedSource as Partial<NodeSummary>);
    }
}

/**
 * ResourceSubresources captures which well-known subresources are supported.
 */
export class ResourceSubresources {
    "scale": boolean;
    "status": boolean;

    /** Creates a new ResourceSubresources instance. */
    constructor($$source: Partial<ResourceSubresources> = {}) {
        if (!("scale" in $$source)) {
            this["scale"] = false;
        }
        if (!("status" in $$source)) {
            this["status"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ResourceSubresources instance from a string or object.
     */
    static createFrom($$source: any = {}): ResourceSubresources {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ResourceSubresources($$parsedSource as Partial<ResourceSubresources>);
    }
}

/**
 * ScaleSubresourceSpec captures the paths the CRD declared for its scale
 * subresource. Defaults are "spec.replicas" / "status.replicas".
 */
export class ScaleSubresourceSpec {
    "specReplicasPath": string;
    "statusReplicasPath": string;

    /** Creates a new ScaleSubresourceSpec instance. */
    constructor($$source: Partial<ScaleSubresourceSpec> = {}) {
        if (!("specReplicasPath" in $$source)) {
            this["specReplicasPath"] = "";
        }
        if (!("statusReplicasPath" in $$source)) {
            this["statusReplicasPath"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ScaleSubresourceSpec instance from a string or object.
     */
    static createFrom($$source: any = {}): ScaleSubresourceSpec {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ScaleSubresourceSpec($$parsedSource as Partial<ScaleSubresourceSpec>);
    }
}

// Private type creation functions
const $$createType0 = ResourceSubresources.createFrom;
const $$createType1 = AdditionalPrinterColumn.createFrom;
const $$createType2 = $Create.Array($$createType1);
const $$createType3 = ScaleSubresourceSpec.createFrom;
const $$createType4 = $Create.Nullable($$createType3);
const $$createType5 = APIServerHealth.createFrom;
const $$createType6 = ComponentHealth.createFrom;
const $$createType7 = $Create.Array($$createType6);
const $$createType8 = NodeSummary.createFrom;
