// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class Action {
    "name": string;
    "label": string;
    "disabledWhen"?: string;
    "disabledReason"?: string;

    /** Creates a new Action instance. */
    constructor($$source: Partial<Action> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("label" in $$source)) {
            this["label"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Action instance from a string or object.
     */
    static createFrom($$source: any = {}): Action {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Action($$parsedSource as Partial<Action>);
    }
}

export enum AlignType {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    AlignLeft = "left",
    AlignRight = "right",
    AlignCenter = "center",
};

export class ApplyResult {
    "gvr": string;
    "namespace": string;
    "name": string;

    /**
     * "created" | "configured" | "unchanged"
     */
    "action": string;
    "error"?: string;

    /** Creates a new ApplyResult instance. */
    constructor($$source: Partial<ApplyResult> = {}) {
        if (!("gvr" in $$source)) {
            this["gvr"] = "";
        }
        if (!("namespace" in $$source)) {
            this["namespace"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("action" in $$source)) {
            this["action"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ApplyResult instance from a string or object.
     */
    static createFrom($$source: any = {}): ApplyResult {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ApplyResult($$parsedSource as Partial<ApplyResult>);
    }
}

export class Column {
    "name": string;
    "expr": string;
    "renderType": RenderType;
    "width"?: number;
    "align"?: AlignType;
    "hidden"?: boolean;

    /** Creates a new Column instance. */
    constructor($$source: Partial<Column> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("expr" in $$source)) {
            this["expr"] = "";
        }
        if (!("renderType" in $$source)) {
            this["renderType"] = RenderType.$zero;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Column instance from a string or object.
     */
    static createFrom($$source: any = {}): Column {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Column($$parsedSource as Partial<Column>);
    }
}

export class Descriptor {
    "group": string;
    "version": string;
    "resource": string;
    "kind"?: string;
    "columns": Column[];
    "overviewFields"?: OverviewField[];
    "detailPanels"?: string[];
    "actions"?: Action[];
    "clusterScoped"?: boolean;

    /**
     * IsVirtual marks a descriptor as backed by a VirtualBackend rather than
     * the dynamic Kubernetes client. Engine and WatchManager dispatch to a
     * registered virtual source when this is true.
     */
    "isVirtual"?: boolean;

    /**
     * GroupLabel is a synthetic sidebar group label (e.g. "Helm"). Optional.
     */
    "groupLabel"?: string;

    /**
     * Available signals whether the descriptor is currently usable on the
     * active cluster. Defaults to true; toggled by the registry via
     * SetAvailable for capability-gated entries (e.g. Helm releases when no
     * helm secrets are present yet).
     * 
     * Read this field via Registry.IsAvailable(gvr) — direct access races with
     * concurrent SetAvailable calls. The JSON tag is preserved so the field
     * serializes correctly when the Registry snapshots descriptors for the
     * frontend under its own lock.
     */
    "available": boolean;

    /** Creates a new Descriptor instance. */
    constructor($$source: Partial<Descriptor> = {}) {
        if (!("group" in $$source)) {
            this["group"] = "";
        }
        if (!("version" in $$source)) {
            this["version"] = "";
        }
        if (!("resource" in $$source)) {
            this["resource"] = "";
        }
        if (!("columns" in $$source)) {
            this["columns"] = [];
        }
        if (!("available" in $$source)) {
            this["available"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Descriptor instance from a string or object.
     */
    static createFrom($$source: any = {}): Descriptor {
        const $$createField4_0 = $$createType1;
        const $$createField5_0 = $$createType3;
        const $$createField6_0 = $$createType4;
        const $$createField7_0 = $$createType6;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("columns" in $$parsedSource) {
            $$parsedSource["columns"] = $$createField4_0($$parsedSource["columns"]);
        }
        if ("overviewFields" in $$parsedSource) {
            $$parsedSource["overviewFields"] = $$createField5_0($$parsedSource["overviewFields"]);
        }
        if ("detailPanels" in $$parsedSource) {
            $$parsedSource["detailPanels"] = $$createField6_0($$parsedSource["detailPanels"]);
        }
        if ("actions" in $$parsedSource) {
            $$parsedSource["actions"] = $$createField7_0($$parsedSource["actions"]);
        }
        return new Descriptor($$parsedSource as Partial<Descriptor>);
    }
}

export class EnricherRegistry {

    /** Creates a new EnricherRegistry instance. */
    constructor($$source: Partial<EnricherRegistry> = {}) {

        Object.assign(this, $$source);
    }

    /**
     * Creates a new EnricherRegistry instance from a string or object.
     */
    static createFrom($$source: any = {}): EnricherRegistry {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new EnricherRegistry($$parsedSource as Partial<EnricherRegistry>);
    }
}

export class OverviewField {
    "label": string;
    "expr": string;
    "renderType": RenderType;

    /** Creates a new OverviewField instance. */
    constructor($$source: Partial<OverviewField> = {}) {
        if (!("label" in $$source)) {
            this["label"] = "";
        }
        if (!("expr" in $$source)) {
            this["expr"] = "";
        }
        if (!("renderType" in $$source)) {
            this["renderType"] = RenderType.$zero;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new OverviewField instance from a string or object.
     */
    static createFrom($$source: any = {}): OverviewField {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new OverviewField($$parsedSource as Partial<OverviewField>);
    }
}

export class Registry {

    /** Creates a new Registry instance. */
    constructor($$source: Partial<Registry> = {}) {

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Registry instance from a string or object.
     */
    static createFrom($$source: any = {}): Registry {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Registry($$parsedSource as Partial<Registry>);
    }
}

export enum RenderType {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    RenderText = "text",
    RenderBadge = "badge",
    RenderAge = "age",
    RenderProgress = "progress",
};

export class ResourceEngine {

    /** Creates a new ResourceEngine instance. */
    constructor($$source: Partial<ResourceEngine> = {}) {

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ResourceEngine instance from a string or object.
     */
    static createFrom($$source: any = {}): ResourceEngine {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ResourceEngine($$parsedSource as Partial<ResourceEngine>);
    }
}

/**
 * Template is a named YAML scaffold for creating a Kubernetes resource.
 */
export class Template {
    "gvr": string;
    "name": string;
    "description": string;
    "content": string;
    "source": string;

    /** Creates a new Template instance. */
    constructor($$source: Partial<Template> = {}) {
        if (!("gvr" in $$source)) {
            this["gvr"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("description" in $$source)) {
            this["description"] = "";
        }
        if (!("content" in $$source)) {
            this["content"] = "";
        }
        if (!("source" in $$source)) {
            this["source"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Template instance from a string or object.
     */
    static createFrom($$source: any = {}): Template {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Template($$parsedSource as Partial<Template>);
    }
}

// Private type creation functions
const $$createType0 = Column.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = OverviewField.createFrom;
const $$createType3 = $Create.Array($$createType2);
const $$createType4 = $Create.Array($Create.Any);
const $$createType5 = Action.createFrom;
const $$createType6 = $Create.Array($$createType5);
