// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class LogOptions {
    "follow": boolean;
    "tailLines": number | null;
    "timestamps": boolean;
    "previous": boolean;
    "container": string;

    /** Creates a new LogOptions instance. */
    constructor($$source: Partial<LogOptions> = {}) {
        if (!("follow" in $$source)) {
            this["follow"] = false;
        }
        if (!("tailLines" in $$source)) {
            this["tailLines"] = null;
        }
        if (!("timestamps" in $$source)) {
            this["timestamps"] = false;
        }
        if (!("previous" in $$source)) {
            this["previous"] = false;
        }
        if (!("container" in $$source)) {
            this["container"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new LogOptions instance from a string or object.
     */
    static createFrom($$source: any = {}): LogOptions {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new LogOptions($$parsedSource as Partial<LogOptions>);
    }
}

export class Streamer {

    /** Creates a new Streamer instance. */
    constructor($$source: Partial<Streamer> = {}) {

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Streamer instance from a string or object.
     */
    static createFrom($$source: any = {}): Streamer {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Streamer($$parsedSource as Partial<Streamer>);
    }
}
