// @ts-nocheck
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * Annotation is a vertical event marker on the graph.
 */
export class Annotation {
    /**
     * Creates a new Annotation instance.
     * @param {Partial<Annotation>} [$$source = {}] - The source object to create the Annotation.
     */
    constructor($$source = {}) {
        if (!("t" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["t"] = 0;
        }
        if (!("label" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["label"] = "";
        }
        if (!("severity" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["severity"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Annotation instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Annotation}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Annotation(/** @type {Partial<Annotation>} */($$parsedSource));
    }
}

/**
 * MetricResult is the response for a single metric query.
 */
export class MetricResult {
    /**
     * Creates a new MetricResult instance.
     * @param {Partial<MetricResult>} [$$source = {}] - The source object to create the MetricResult.
     */
    constructor($$source = {}) {
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("unit" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["unit"] = "";
        }
        if (!("series" in $$source)) {
            /**
             * @member
             * @type {TimeSeries[]}
             */
            this["series"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new MetricResult instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {MetricResult}
     */
    static createFrom($$source = {}) {
        const $$createField2_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("series" in $$parsedSource) {
            $$parsedSource["series"] = $$createField2_0($$parsedSource["series"]);
        }
        return new MetricResult(/** @type {Partial<MetricResult>} */($$parsedSource));
    }
}

/**
 * MetricsCapability describes what metric sources are available for a cluster.
 */
export class MetricsCapability {
    /**
     * Creates a new MetricsCapability instance.
     * @param {Partial<MetricsCapability>} [$$source = {}] - The source object to create the MetricsCapability.
     */
    constructor($$source = {}) {
        if (!("hasMetricsServer" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["hasMetricsServer"] = false;
        }
        if (!("hasPrometheus" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["hasPrometheus"] = false;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["prometheusUrl"] = undefined;
        }
        if (!("hasKsm" in $$source)) {
            /**
             * kube-state-metrics is available
             * @member
             * @type {boolean}
             */
            this["hasKsm"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new MetricsCapability instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {MetricsCapability}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new MetricsCapability(/** @type {Partial<MetricsCapability>} */($$parsedSource));
    }
}

/**
 * MetricsResponse is the full response for a resource's metrics tab.
 */
export class MetricsResponse {
    /**
     * Creates a new MetricsResponse instance.
     * @param {Partial<MetricsResponse>} [$$source = {}] - The source object to create the MetricsResponse.
     */
    constructor($$source = {}) {
        if (!("metrics" in $$source)) {
            /**
             * @member
             * @type {MetricResult[]}
             */
            this["metrics"] = [];
        }
        if (!("thresholds" in $$source)) {
            /**
             * @member
             * @type {ThresholdLine[]}
             */
            this["thresholds"] = [];
        }
        if (!("annotations" in $$source)) {
            /**
             * @member
             * @type {Annotation[]}
             */
            this["annotations"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new MetricsResponse instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {MetricsResponse}
     */
    static createFrom($$source = {}) {
        const $$createField0_0 = $$createType3;
        const $$createField1_0 = $$createType5;
        const $$createField2_0 = $$createType7;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("metrics" in $$parsedSource) {
            $$parsedSource["metrics"] = $$createField0_0($$parsedSource["metrics"]);
        }
        if ("thresholds" in $$parsedSource) {
            $$parsedSource["thresholds"] = $$createField1_0($$parsedSource["thresholds"]);
        }
        if ("annotations" in $$parsedSource) {
            $$parsedSource["annotations"] = $$createField2_0($$parsedSource["annotations"]);
        }
        return new MetricsResponse(/** @type {Partial<MetricsResponse>} */($$parsedSource));
    }
}

/**
 * ThresholdLine is a horizontal overlay (requests/limits).
 */
export class ThresholdLine {
    /**
     * Creates a new ThresholdLine instance.
     * @param {Partial<ThresholdLine>} [$$source = {}] - The source object to create the ThresholdLine.
     */
    constructor($$source = {}) {
        if (!("label" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["label"] = "";
        }
        if (!("series" in $$source)) {
            /**
             * @member
             * @type {TimeSeriesPoint[]}
             */
            this["series"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ThresholdLine instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ThresholdLine}
     */
    static createFrom($$source = {}) {
        const $$createField1_0 = $$createType9;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("series" in $$parsedSource) {
            $$parsedSource["series"] = $$createField1_0($$parsedSource["series"]);
        }
        return new ThresholdLine(/** @type {Partial<ThresholdLine>} */($$parsedSource));
    }
}

/**
 * TimeSeries is a labeled series of points.
 */
export class TimeSeries {
    /**
     * Creates a new TimeSeries instance.
     * @param {Partial<TimeSeries>} [$$source = {}] - The source object to create the TimeSeries.
     */
    constructor($$source = {}) {
        if (!("labels" in $$source)) {
            /**
             * @member
             * @type {{ [_ in string]?: string }}
             */
            this["labels"] = {};
        }
        if (!("points" in $$source)) {
            /**
             * @member
             * @type {TimeSeriesPoint[]}
             */
            this["points"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TimeSeries instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {TimeSeries}
     */
    static createFrom($$source = {}) {
        const $$createField0_0 = $$createType10;
        const $$createField1_0 = $$createType9;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("labels" in $$parsedSource) {
            $$parsedSource["labels"] = $$createField0_0($$parsedSource["labels"]);
        }
        if ("points" in $$parsedSource) {
            $$parsedSource["points"] = $$createField1_0($$parsedSource["points"]);
        }
        return new TimeSeries(/** @type {Partial<TimeSeries>} */($$parsedSource));
    }
}

/**
 * TimeSeriesPoint is a single (timestamp, value) sample.
 */
export class TimeSeriesPoint {
    /**
     * Creates a new TimeSeriesPoint instance.
     * @param {Partial<TimeSeriesPoint>} [$$source = {}] - The source object to create the TimeSeriesPoint.
     */
    constructor($$source = {}) {
        if (!("t" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["t"] = 0;
        }
        if (!("v" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["v"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TimeSeriesPoint instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {TimeSeriesPoint}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new TimeSeriesPoint(/** @type {Partial<TimeSeriesPoint>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = TimeSeries.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = MetricResult.createFrom;
const $$createType3 = $Create.Array($$createType2);
const $$createType4 = ThresholdLine.createFrom;
const $$createType5 = $Create.Array($$createType4);
const $$createType6 = Annotation.createFrom;
const $$createType7 = $Create.Array($$createType6);
const $$createType8 = TimeSeriesPoint.createFrom;
const $$createType9 = $Create.Array($$createType8);
const $$createType10 = $Create.Map($Create.Any, $Create.Any);
