// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * Annotation is a vertical event marker on the graph.
 */
export class Annotation {
    "t": number;
    "label": string;
    "severity": string;

    /** Creates a new Annotation instance. */
    constructor($$source: Partial<Annotation> = {}) {
        if (!("t" in $$source)) {
            this["t"] = 0;
        }
        if (!("label" in $$source)) {
            this["label"] = "";
        }
        if (!("severity" in $$source)) {
            this["severity"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Annotation instance from a string or object.
     */
    static createFrom($$source: any = {}): Annotation {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Annotation($$parsedSource as Partial<Annotation>);
    }
}

/**
 * MetricResult is the response for a single metric query.
 */
export class MetricResult {
    "name": string;
    "unit": string;
    "series": TimeSeries[];

    /** Creates a new MetricResult instance. */
    constructor($$source: Partial<MetricResult> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("unit" in $$source)) {
            this["unit"] = "";
        }
        if (!("series" in $$source)) {
            this["series"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new MetricResult instance from a string or object.
     */
    static createFrom($$source: any = {}): MetricResult {
        const $$createField2_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("series" in $$parsedSource) {
            $$parsedSource["series"] = $$createField2_0($$parsedSource["series"]);
        }
        return new MetricResult($$parsedSource as Partial<MetricResult>);
    }
}

/**
 * MetricsCapability describes what metric sources are available for a cluster.
 */
export class MetricsCapability {
    "hasMetricsServer": boolean;
    "hasPrometheus": boolean;
    "prometheusUrl"?: string;

    /**
     * kube-state-metrics is available
     */
    "hasKsm": boolean;

    /** Creates a new MetricsCapability instance. */
    constructor($$source: Partial<MetricsCapability> = {}) {
        if (!("hasMetricsServer" in $$source)) {
            this["hasMetricsServer"] = false;
        }
        if (!("hasPrometheus" in $$source)) {
            this["hasPrometheus"] = false;
        }
        if (!("hasKsm" in $$source)) {
            this["hasKsm"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new MetricsCapability instance from a string or object.
     */
    static createFrom($$source: any = {}): MetricsCapability {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new MetricsCapability($$parsedSource as Partial<MetricsCapability>);
    }
}

/**
 * MetricsResponse is the full response for a resource's metrics tab.
 */
export class MetricsResponse {
    "metrics": MetricResult[];
    "thresholds": ThresholdLine[];
    "annotations": Annotation[];

    /** Creates a new MetricsResponse instance. */
    constructor($$source: Partial<MetricsResponse> = {}) {
        if (!("metrics" in $$source)) {
            this["metrics"] = [];
        }
        if (!("thresholds" in $$source)) {
            this["thresholds"] = [];
        }
        if (!("annotations" in $$source)) {
            this["annotations"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new MetricsResponse instance from a string or object.
     */
    static createFrom($$source: any = {}): MetricsResponse {
        const $$createField0_0 = $$createType3;
        const $$createField1_0 = $$createType5;
        const $$createField2_0 = $$createType7;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("metrics" in $$parsedSource) {
            $$parsedSource["metrics"] = $$createField0_0($$parsedSource["metrics"]);
        }
        if ("thresholds" in $$parsedSource) {
            $$parsedSource["thresholds"] = $$createField1_0($$parsedSource["thresholds"]);
        }
        if ("annotations" in $$parsedSource) {
            $$parsedSource["annotations"] = $$createField2_0($$parsedSource["annotations"]);
        }
        return new MetricsResponse($$parsedSource as Partial<MetricsResponse>);
    }
}

/**
 * ThresholdLine is a horizontal overlay (requests/limits).
 */
export class ThresholdLine {
    "label": string;
    "series": TimeSeriesPoint[];

    /** Creates a new ThresholdLine instance. */
    constructor($$source: Partial<ThresholdLine> = {}) {
        if (!("label" in $$source)) {
            this["label"] = "";
        }
        if (!("series" in $$source)) {
            this["series"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ThresholdLine instance from a string or object.
     */
    static createFrom($$source: any = {}): ThresholdLine {
        const $$createField1_0 = $$createType9;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("series" in $$parsedSource) {
            $$parsedSource["series"] = $$createField1_0($$parsedSource["series"]);
        }
        return new ThresholdLine($$parsedSource as Partial<ThresholdLine>);
    }
}

/**
 * TimeSeries is a labeled series of points.
 */
export class TimeSeries {
    "labels": { [_ in string]?: string };
    "points": TimeSeriesPoint[];

    /** Creates a new TimeSeries instance. */
    constructor($$source: Partial<TimeSeries> = {}) {
        if (!("labels" in $$source)) {
            this["labels"] = {};
        }
        if (!("points" in $$source)) {
            this["points"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TimeSeries instance from a string or object.
     */
    static createFrom($$source: any = {}): TimeSeries {
        const $$createField0_0 = $$createType10;
        const $$createField1_0 = $$createType9;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("labels" in $$parsedSource) {
            $$parsedSource["labels"] = $$createField0_0($$parsedSource["labels"]);
        }
        if ("points" in $$parsedSource) {
            $$parsedSource["points"] = $$createField1_0($$parsedSource["points"]);
        }
        return new TimeSeries($$parsedSource as Partial<TimeSeries>);
    }
}

/**
 * TimeSeriesPoint is a single (timestamp, value) sample.
 */
export class TimeSeriesPoint {
    "t": number;
    "v": number;

    /** Creates a new TimeSeriesPoint instance. */
    constructor($$source: Partial<TimeSeriesPoint> = {}) {
        if (!("t" in $$source)) {
            this["t"] = 0;
        }
        if (!("v" in $$source)) {
            this["v"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TimeSeriesPoint instance from a string or object.
     */
    static createFrom($$source: any = {}): TimeSeriesPoint {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new TimeSeriesPoint($$parsedSource as Partial<TimeSeriesPoint>);
    }
}

// Private type creation functions
const $$createType0 = TimeSeries.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = MetricResult.createFrom;
const $$createType3 = $Create.Array($$createType2);
const $$createType4 = ThresholdLine.createFrom;
const $$createType5 = $Create.Array($$createType4);
const $$createType6 = Annotation.createFrom;
const $$createType7 = $Create.Array($$createType6);
const $$createType8 = TimeSeriesPoint.createFrom;
const $$createType9 = $Create.Array($$createType8);
const $$createType10 = $Create.Map($Create.Any, $Create.Any);
