// @ts-nocheck
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class ClusterPrefs {
    /**
     * Creates a new ClusterPrefs instance.
     * @param {Partial<ClusterPrefs>} [$$source = {}] - The source object to create the ClusterPrefs.
     */
    constructor($$source = {}) {
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {boolean | null | undefined}
             */
            this["readOnly"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {boolean | null | undefined}
             */
            this["compactRows"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | null | undefined}
             */
            this["accentColor"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | null | undefined}
             */
            this["displayName"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {MetricsConfig | null | undefined}
             */
            this["metrics"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {{ [_ in string]?: GVRColumnPrefs | null } | undefined}
             */
            this["columnPrefs"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string[] | undefined}
             */
            this["favoriteNamespaces"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {{ [_ in string]?: SavedFilter[] } | undefined}
             */
            this["savedFilters"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {VolumeBrowserConfig | null | undefined}
             */
            this["volumeBrowser"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ClusterPrefs instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ClusterPrefs}
     */
    static createFrom($$source = {}) {
        const $$createField4_0 = $$createType1;
        const $$createField5_0 = $$createType4;
        const $$createField6_0 = $$createType5;
        const $$createField7_0 = $$createType8;
        const $$createField8_0 = $$createType10;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("metrics" in $$parsedSource) {
            $$parsedSource["metrics"] = $$createField4_0($$parsedSource["metrics"]);
        }
        if ("columnPrefs" in $$parsedSource) {
            $$parsedSource["columnPrefs"] = $$createField5_0($$parsedSource["columnPrefs"]);
        }
        if ("favoriteNamespaces" in $$parsedSource) {
            $$parsedSource["favoriteNamespaces"] = $$createField6_0($$parsedSource["favoriteNamespaces"]);
        }
        if ("savedFilters" in $$parsedSource) {
            $$parsedSource["savedFilters"] = $$createField7_0($$parsedSource["savedFilters"]);
        }
        if ("volumeBrowser" in $$parsedSource) {
            $$parsedSource["volumeBrowser"] = $$createField8_0($$parsedSource["volumeBrowser"]);
        }
        return new ClusterPrefs(/** @type {Partial<ClusterPrefs>} */($$parsedSource));
    }
}

export class ColumnSettings {
    /**
     * Creates a new ColumnSettings instance.
     * @param {Partial<ColumnSettings>} [$$source = {}] - The source object to create the ColumnSettings.
     */
    constructor($$source = {}) {
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {number | undefined}
             */
            this["width"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ColumnSettings instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ColumnSettings}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ColumnSettings(/** @type {Partial<ColumnSettings>} */($$parsedSource));
    }
}

export class Config {
    /**
     * Creates a new Config instance.
     * @param {Partial<Config>} [$$source = {}] - The source object to create the Config.
     */
    constructor($$source = {}) {
        if (!("theme" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["theme"] = "";
        }
        if (!("kubeconfigPaths" in $$source)) {
            /**
             * @member
             * @type {string[]}
             */
            this["kubeconfigPaths"] = [];
        }
        if (!("terminalWebGL" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["terminalWebGL"] = false;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string[] | undefined}
             */
            this["disabledPlugins"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string[] | undefined}
             */
            this["insecureRegistries"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {boolean | undefined}
             */
            this["insecureSkipTLSVerify"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {{ [_ in string]?: MetricsConfig | null } | undefined}
             */
            this["metrics"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {{ [_ in string]?: GVRColumnPrefs | null } | undefined}
             */
            this["columnPrefs"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {boolean | undefined}
             */
            this["compactRows"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {boolean | undefined}
             */
            this["readOnly"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {{ [_ in string]?: SavedPortForward[] } | undefined}
             */
            this["portForwards"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {{ [_ in string]?: ClusterPrefs | null } | undefined}
             */
            this["clusters"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {{ [_ in string]?: string } | undefined}
             */
            this["keybindings"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {{ [_ in string]?: SavedFilter[] } | undefined}
             */
            this["savedFilters"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["startupBehavior"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["startupCluster"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["accentColor"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {number | undefined}
             */
            this["fontSize"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {boolean | null | undefined}
             */
            this["contextualAutocomplete"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {VolumeBrowserConfig | undefined}
             */
            this["volumeBrowser"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Config instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Config}
     */
    static createFrom($$source = {}) {
        const $$createField1_0 = $$createType5;
        const $$createField3_0 = $$createType5;
        const $$createField4_0 = $$createType5;
        const $$createField6_0 = $$createType11;
        const $$createField7_0 = $$createType4;
        const $$createField10_0 = $$createType14;
        const $$createField11_0 = $$createType17;
        const $$createField12_0 = $$createType18;
        const $$createField13_0 = $$createType8;
        const $$createField19_0 = $$createType9;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("kubeconfigPaths" in $$parsedSource) {
            $$parsedSource["kubeconfigPaths"] = $$createField1_0($$parsedSource["kubeconfigPaths"]);
        }
        if ("disabledPlugins" in $$parsedSource) {
            $$parsedSource["disabledPlugins"] = $$createField3_0($$parsedSource["disabledPlugins"]);
        }
        if ("insecureRegistries" in $$parsedSource) {
            $$parsedSource["insecureRegistries"] = $$createField4_0($$parsedSource["insecureRegistries"]);
        }
        if ("metrics" in $$parsedSource) {
            $$parsedSource["metrics"] = $$createField6_0($$parsedSource["metrics"]);
        }
        if ("columnPrefs" in $$parsedSource) {
            $$parsedSource["columnPrefs"] = $$createField7_0($$parsedSource["columnPrefs"]);
        }
        if ("portForwards" in $$parsedSource) {
            $$parsedSource["portForwards"] = $$createField10_0($$parsedSource["portForwards"]);
        }
        if ("clusters" in $$parsedSource) {
            $$parsedSource["clusters"] = $$createField11_0($$parsedSource["clusters"]);
        }
        if ("keybindings" in $$parsedSource) {
            $$parsedSource["keybindings"] = $$createField12_0($$parsedSource["keybindings"]);
        }
        if ("savedFilters" in $$parsedSource) {
            $$parsedSource["savedFilters"] = $$createField13_0($$parsedSource["savedFilters"]);
        }
        if ("volumeBrowser" in $$parsedSource) {
            $$parsedSource["volumeBrowser"] = $$createField19_0($$parsedSource["volumeBrowser"]);
        }
        return new Config(/** @type {Partial<Config>} */($$parsedSource));
    }
}

export class GVRColumnPrefs {
    /**
     * Creates a new GVRColumnPrefs instance.
     * @param {Partial<GVRColumnPrefs>} [$$source = {}] - The source object to create the GVRColumnPrefs.
     */
    constructor($$source = {}) {
        if (!("columns" in $$source)) {
            /**
             * @member
             * @type {{ [_ in string]?: ColumnSettings }}
             */
            this["columns"] = {};
        }
        if (!("order" in $$source)) {
            /**
             * @member
             * @type {string[]}
             */
            this["order"] = [];
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {SortPrefs | null | undefined}
             */
            this["sort"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string[] | undefined}
             */
            this["pinned"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new GVRColumnPrefs instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {GVRColumnPrefs}
     */
    static createFrom($$source = {}) {
        const $$createField0_0 = $$createType20;
        const $$createField1_0 = $$createType5;
        const $$createField2_0 = $$createType22;
        const $$createField3_0 = $$createType5;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("columns" in $$parsedSource) {
            $$parsedSource["columns"] = $$createField0_0($$parsedSource["columns"]);
        }
        if ("order" in $$parsedSource) {
            $$parsedSource["order"] = $$createField1_0($$parsedSource["order"]);
        }
        if ("sort" in $$parsedSource) {
            $$parsedSource["sort"] = $$createField2_0($$parsedSource["sort"]);
        }
        if ("pinned" in $$parsedSource) {
            $$parsedSource["pinned"] = $$createField3_0($$parsedSource["pinned"]);
        }
        return new GVRColumnPrefs(/** @type {Partial<GVRColumnPrefs>} */($$parsedSource));
    }
}

export class MetricsConfig {
    /**
     * Creates a new MetricsConfig instance.
     * @param {Partial<MetricsConfig>} [$$source = {}] - The source object to create the MetricsConfig.
     */
    constructor($$source = {}) {
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["prometheusUrl"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new MetricsConfig instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {MetricsConfig}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new MetricsConfig(/** @type {Partial<MetricsConfig>} */($$parsedSource));
    }
}

export class ResolvedPrefs {
    /**
     * Creates a new ResolvedPrefs instance.
     * @param {Partial<ResolvedPrefs>} [$$source = {}] - The source object to create the ResolvedPrefs.
     */
    constructor($$source = {}) {
        if (!("theme" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["theme"] = "";
        }
        if (!("accentColor" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["accentColor"] = "";
        }
        if (!("fontSize" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["fontSize"] = 0;
        }
        if (!("compactRows" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["compactRows"] = false;
        }
        if (!("readOnly" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["readOnly"] = false;
        }
        if (!("terminalWebGL" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["terminalWebGL"] = false;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {MetricsConfig | null | undefined}
             */
            this["metrics"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {{ [_ in string]?: GVRColumnPrefs | null } | undefined}
             */
            this["columnPrefs"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string[] | undefined}
             */
            this["favoriteNamespaces"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {{ [_ in string]?: string } | undefined}
             */
            this["keybindings"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {{ [_ in string]?: SavedFilter[] } | undefined}
             */
            this["savedFilters"] = undefined;
        }
        if (!("contextualAutocomplete" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["contextualAutocomplete"] = false;
        }
        if (!("volumeBrowser" in $$source)) {
            /**
             * @member
             * @type {VolumeBrowserConfig}
             */
            this["volumeBrowser"] = (new VolumeBrowserConfig());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ResolvedPrefs instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ResolvedPrefs}
     */
    static createFrom($$source = {}) {
        const $$createField6_0 = $$createType1;
        const $$createField7_0 = $$createType4;
        const $$createField8_0 = $$createType5;
        const $$createField9_0 = $$createType18;
        const $$createField10_0 = $$createType8;
        const $$createField12_0 = $$createType9;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("metrics" in $$parsedSource) {
            $$parsedSource["metrics"] = $$createField6_0($$parsedSource["metrics"]);
        }
        if ("columnPrefs" in $$parsedSource) {
            $$parsedSource["columnPrefs"] = $$createField7_0($$parsedSource["columnPrefs"]);
        }
        if ("favoriteNamespaces" in $$parsedSource) {
            $$parsedSource["favoriteNamespaces"] = $$createField8_0($$parsedSource["favoriteNamespaces"]);
        }
        if ("keybindings" in $$parsedSource) {
            $$parsedSource["keybindings"] = $$createField9_0($$parsedSource["keybindings"]);
        }
        if ("savedFilters" in $$parsedSource) {
            $$parsedSource["savedFilters"] = $$createField10_0($$parsedSource["savedFilters"]);
        }
        if ("volumeBrowser" in $$parsedSource) {
            $$parsedSource["volumeBrowser"] = $$createField12_0($$parsedSource["volumeBrowser"]);
        }
        return new ResolvedPrefs(/** @type {Partial<ResolvedPrefs>} */($$parsedSource));
    }
}

export class ResourceReqs {
    /**
     * Creates a new ResourceReqs instance.
     * @param {Partial<ResourceReqs>} [$$source = {}] - The source object to create the ResourceReqs.
     */
    constructor($$source = {}) {
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {{ [_ in string]?: string } | undefined}
             */
            this["requests"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {{ [_ in string]?: string } | undefined}
             */
            this["limits"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ResourceReqs instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ResourceReqs}
     */
    static createFrom($$source = {}) {
        const $$createField0_0 = $$createType18;
        const $$createField1_0 = $$createType18;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("requests" in $$parsedSource) {
            $$parsedSource["requests"] = $$createField0_0($$parsedSource["requests"]);
        }
        if ("limits" in $$parsedSource) {
            $$parsedSource["limits"] = $$createField1_0($$parsedSource["limits"]);
        }
        return new ResourceReqs(/** @type {Partial<ResourceReqs>} */($$parsedSource));
    }
}

export class SavedFilter {
    /**
     * Creates a new SavedFilter instance.
     * @param {Partial<SavedFilter>} [$$source = {}] - The source object to create the SavedFilter.
     */
    constructor($$source = {}) {
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {{ [_ in string]?: string } | undefined}
             */
            this["labels"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {{ [_ in string]?: string } | undefined}
             */
            this["annotations"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["search"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SavedFilter instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {SavedFilter}
     */
    static createFrom($$source = {}) {
        const $$createField1_0 = $$createType18;
        const $$createField2_0 = $$createType18;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("labels" in $$parsedSource) {
            $$parsedSource["labels"] = $$createField1_0($$parsedSource["labels"]);
        }
        if ("annotations" in $$parsedSource) {
            $$parsedSource["annotations"] = $$createField2_0($$parsedSource["annotations"]);
        }
        return new SavedFilter(/** @type {Partial<SavedFilter>} */($$parsedSource));
    }
}

export class SavedPortForward {
    /**
     * Creates a new SavedPortForward instance.
     * @param {Partial<SavedPortForward>} [$$source = {}] - The source object to create the SavedPortForward.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("namespace" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["namespace"] = "";
        }
        if (!("resource" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["resource"] = "";
        }
        if (!("targetKind" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["targetKind"] = "";
        }
        if (!("targetName" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["targetName"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["targetGVR"] = undefined;
        }
        if (!("localPort" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["localPort"] = 0;
        }
        if (!("remotePort" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["remotePort"] = 0;
        }
        if (!("enabled" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["enabled"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SavedPortForward instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {SavedPortForward}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SavedPortForward(/** @type {Partial<SavedPortForward>} */($$parsedSource));
    }
}

export class SortPrefs {
    /**
     * Creates a new SortPrefs instance.
     * @param {Partial<SortPrefs>} [$$source = {}] - The source object to create the SortPrefs.
     */
    constructor($$source = {}) {
        if (!("column" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["column"] = "";
        }
        if (!("direction" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["direction"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SortPrefs instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {SortPrefs}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SortPrefs(/** @type {Partial<SortPrefs>} */($$parsedSource));
    }
}

export class VolumeBrowserConfig {
    /**
     * Creates a new VolumeBrowserConfig instance.
     * @param {Partial<VolumeBrowserConfig>} [$$source = {}] - The source object to create the VolumeBrowserConfig.
     */
    constructor($$source = {}) {
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["image"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["mountPath"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {boolean | null | undefined}
             */
            this["readOnly"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {number | null | undefined}
             */
            this["activeDeadlineSeconds"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {ResourceReqs | null | undefined}
             */
            this["resources"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {{ [_ in string]?: string } | undefined}
             */
            this["nodeSelector"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {{ [_ in string]?: any }[] | undefined}
             */
            this["tolerations"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {boolean | null | undefined}
             */
            this["promptBeforeSpawn"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["orphanCleanupOnStartup"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new VolumeBrowserConfig instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {VolumeBrowserConfig}
     */
    static createFrom($$source = {}) {
        const $$createField4_0 = $$createType24;
        const $$createField5_0 = $$createType18;
        const $$createField6_0 = $$createType26;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("resources" in $$parsedSource) {
            $$parsedSource["resources"] = $$createField4_0($$parsedSource["resources"]);
        }
        if ("nodeSelector" in $$parsedSource) {
            $$parsedSource["nodeSelector"] = $$createField5_0($$parsedSource["nodeSelector"]);
        }
        if ("tolerations" in $$parsedSource) {
            $$parsedSource["tolerations"] = $$createField6_0($$parsedSource["tolerations"]);
        }
        return new VolumeBrowserConfig(/** @type {Partial<VolumeBrowserConfig>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = MetricsConfig.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = GVRColumnPrefs.createFrom;
const $$createType3 = $Create.Nullable($$createType2);
const $$createType4 = $Create.Map($Create.Any, $$createType3);
const $$createType5 = $Create.Array($Create.Any);
const $$createType6 = SavedFilter.createFrom;
const $$createType7 = $Create.Array($$createType6);
const $$createType8 = $Create.Map($Create.Any, $$createType7);
const $$createType9 = VolumeBrowserConfig.createFrom;
const $$createType10 = $Create.Nullable($$createType9);
const $$createType11 = $Create.Map($Create.Any, $$createType1);
const $$createType12 = SavedPortForward.createFrom;
const $$createType13 = $Create.Array($$createType12);
const $$createType14 = $Create.Map($Create.Any, $$createType13);
const $$createType15 = ClusterPrefs.createFrom;
const $$createType16 = $Create.Nullable($$createType15);
const $$createType17 = $Create.Map($Create.Any, $$createType16);
const $$createType18 = $Create.Map($Create.Any, $Create.Any);
const $$createType19 = ColumnSettings.createFrom;
const $$createType20 = $Create.Map($Create.Any, $$createType19);
const $$createType21 = SortPrefs.createFrom;
const $$createType22 = $Create.Nullable($$createType21);
const $$createType23 = ResourceReqs.createFrom;
const $$createType24 = $Create.Nullable($$createType23);
const $$createType25 = $Create.Map($Create.Any, $Create.Any);
const $$createType26 = $Create.Array($$createType25);
