// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class ForwardSpec {
    "id": string;
    "contextName": string;
    "namespace": string;
    "targetKind": TargetKind;
    "targetName": string;
    "targetGVR"?: string;
    "localPort": number;
    "remotePort": number;
    "status": ForwardStatus;
    "podName"?: string;
    "error"?: string;

    /** Creates a new ForwardSpec instance. */
    constructor($$source: Partial<ForwardSpec> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("contextName" in $$source)) {
            this["contextName"] = "";
        }
        if (!("namespace" in $$source)) {
            this["namespace"] = "";
        }
        if (!("targetKind" in $$source)) {
            this["targetKind"] = TargetKind.$zero;
        }
        if (!("targetName" in $$source)) {
            this["targetName"] = "";
        }
        if (!("localPort" in $$source)) {
            this["localPort"] = 0;
        }
        if (!("remotePort" in $$source)) {
            this["remotePort"] = 0;
        }
        if (!("status" in $$source)) {
            this["status"] = ForwardStatus.$zero;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ForwardSpec instance from a string or object.
     */
    static createFrom($$source: any = {}): ForwardSpec {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ForwardSpec($$parsedSource as Partial<ForwardSpec>);
    }
}

export enum ForwardStatus {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    StatusActive = "active",
    StatusReconnecting = "reconnecting",
    StatusFailed = "failed",
    StatusStopped = "stopped",
};

export class Manager {

    /** Creates a new Manager instance. */
    constructor($$source: Partial<Manager> = {}) {

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Manager instance from a string or object.
     */
    static createFrom($$source: any = {}): Manager {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Manager($$parsedSource as Partial<Manager>);
    }
}

export enum TargetKind {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    TargetKindPod = "pod",
    TargetKindStatefulPod = "statefulpod",
    TargetKindSelector = "selector",
};
