// @ts-nocheck
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class LogOptions {
    /**
     * Creates a new LogOptions instance.
     * @param {Partial<LogOptions>} [$$source = {}] - The source object to create the LogOptions.
     */
    constructor($$source = {}) {
        if (!("follow" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["follow"] = false;
        }
        if (!("tailLines" in $$source)) {
            /**
             * @member
             * @type {number | null}
             */
            this["tailLines"] = null;
        }
        if (!("timestamps" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["timestamps"] = false;
        }
        if (!("previous" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["previous"] = false;
        }
        if (!("container" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["container"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new LogOptions instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {LogOptions}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new LogOptions(/** @type {Partial<LogOptions>} */($$parsedSource));
    }
}

export class Streamer {
    /**
     * Creates a new Streamer instance.
     * @param {Partial<Streamer>} [$$source = {}] - The source object to create the Streamer.
     */
    constructor($$source = {}) {

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Streamer instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Streamer}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Streamer(/** @type {Partial<Streamer>} */($$parsedSource));
    }
}
