// @ts-nocheck
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class WatchManager {
    /**
     * Creates a new WatchManager instance.
     * @param {Partial<WatchManager>} [$$source = {}] - The source object to create the WatchManager.
     */
    constructor($$source = {}) {

        Object.assign(this, $$source);
    }

    /**
     * Creates a new WatchManager instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {WatchManager}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new WatchManager(/** @type {Partial<WatchManager>} */($$parsedSource));
    }
}
