// @ts-nocheck
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as time$0 from "../../../../../time/models.js";

/**
 * Hook is a flattened, JSON-friendly view of a single Helm release hook for
 * the UI's "Hooks" detail tab.
 */
export class Hook {
    /**
     * Creates a new Hook instance.
     * @param {Partial<Hook>} [$$source = {}] - The source object to create the Hook.
     */
    constructor($$source = {}) {
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("kind" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["kind"] = "";
        }
        if (!("path" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["path"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string[] | undefined}
             */
            this["events"] = undefined;
        }
        if (!("weight" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["weight"] = 0;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["phase"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["startedAt"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["completedAt"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["manifest"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Hook instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Hook}
     */
    static createFrom($$source = {}) {
        const $$createField3_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("events" in $$parsedSource) {
            $$parsedSource["events"] = $$createField3_0($$parsedSource["events"]);
        }
        return new Hook(/** @type {Partial<Hook>} */($$parsedSource));
    }
}

/**
 * OwnedRef is a single resource owned by a Helm release.
 */
export class OwnedRef {
    /**
     * Creates a new OwnedRef instance.
     * @param {Partial<OwnedRef>} [$$source = {}] - The source object to create the OwnedRef.
     */
    constructor($$source = {}) {
        if (!("APIVersion" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["APIVersion"] = "";
        }
        if (!("Kind" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["Kind"] = "";
        }
        if (!("GVR" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["GVR"] = "";
        }
        if (!("Namespace" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["Namespace"] = "";
        }
        if (!("Name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["Name"] = "";
        }
        if (!("ResourcePolicy" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["ResourcePolicy"] = "";
        }
        if (!("Exists" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["Exists"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new OwnedRef instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {OwnedRef}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new OwnedRef(/** @type {Partial<OwnedRef>} */($$parsedSource));
    }
}

/**
 * Revision is a flattened view of one Helm release revision.
 */
export class Revision {
    /**
     * Creates a new Revision instance.
     * @param {Partial<Revision>} [$$source = {}] - The source object to create the Revision.
     */
    constructor($$source = {}) {
        if (!("Number" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["Number"] = 0;
        }
        if (!("Status" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["Status"] = "";
        }
        if (!("ChartName" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["ChartName"] = "";
        }
        if (!("ChartVersion" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["ChartVersion"] = "";
        }
        if (!("AppVersion" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["AppVersion"] = "";
        }
        if (!("Description" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["Description"] = "";
        }
        if (!("DeployedAt" in $$source)) {
            /**
             * @member
             * @type {time$0.Time}
             */
            this["DeployedAt"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Revision instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Revision}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Revision(/** @type {Partial<Revision>} */($$parsedSource));
    }
}

/**
 * RevisionDiff carries the three textual diffs surfaced to the UI.
 */
export class RevisionDiff {
    /**
     * Creates a new RevisionDiff instance.
     * @param {Partial<RevisionDiff>} [$$source = {}] - The source object to create the RevisionDiff.
     */
    constructor($$source = {}) {
        if (!("Values" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["Values"] = "";
        }
        if (!("ComputedValues" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["ComputedValues"] = "";
        }
        if (!("Manifest" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["Manifest"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new RevisionDiff instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {RevisionDiff}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new RevisionDiff(/** @type {Partial<RevisionDiff>} */($$parsedSource));
    }
}

/**
 * TestResult is returned from a synchronous helm-test run.
 */
export class TestResult {
    /**
     * Creates a new TestResult instance.
     * @param {Partial<TestResult>} [$$source = {}] - The source object to create the TestResult.
     */
    constructor($$source = {}) {
        if (!("Phase" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["Phase"] = "";
        }
        if (!("Logs" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["Logs"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TestResult instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {TestResult}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new TestResult(/** @type {Partial<TestResult>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
