// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as time$0 from "../../../../../time/models.js";

/**
 * Hook is a flattened, JSON-friendly view of a single Helm release hook for
 * the UI's "Hooks" detail tab.
 */
export class Hook {
    "name": string;
    "kind": string;
    "path": string;
    "events"?: string[];
    "weight": number;
    "phase"?: string;
    "startedAt"?: string;
    "completedAt"?: string;
    "manifest"?: string;

    /** Creates a new Hook instance. */
    constructor($$source: Partial<Hook> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("kind" in $$source)) {
            this["kind"] = "";
        }
        if (!("path" in $$source)) {
            this["path"] = "";
        }
        if (!("weight" in $$source)) {
            this["weight"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Hook instance from a string or object.
     */
    static createFrom($$source: any = {}): Hook {
        const $$createField3_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("events" in $$parsedSource) {
            $$parsedSource["events"] = $$createField3_0($$parsedSource["events"]);
        }
        return new Hook($$parsedSource as Partial<Hook>);
    }
}

/**
 * OwnedRef is a single resource owned by a Helm release.
 */
export class OwnedRef {
    "APIVersion": string;
    "Kind": string;
    "GVR": string;
    "Namespace": string;
    "Name": string;
    "ResourcePolicy": string;
    "Exists": boolean;

    /** Creates a new OwnedRef instance. */
    constructor($$source: Partial<OwnedRef> = {}) {
        if (!("APIVersion" in $$source)) {
            this["APIVersion"] = "";
        }
        if (!("Kind" in $$source)) {
            this["Kind"] = "";
        }
        if (!("GVR" in $$source)) {
            this["GVR"] = "";
        }
        if (!("Namespace" in $$source)) {
            this["Namespace"] = "";
        }
        if (!("Name" in $$source)) {
            this["Name"] = "";
        }
        if (!("ResourcePolicy" in $$source)) {
            this["ResourcePolicy"] = "";
        }
        if (!("Exists" in $$source)) {
            this["Exists"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new OwnedRef instance from a string or object.
     */
    static createFrom($$source: any = {}): OwnedRef {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new OwnedRef($$parsedSource as Partial<OwnedRef>);
    }
}

/**
 * Revision is a flattened view of one Helm release revision.
 */
export class Revision {
    "Number": number;
    "Status": string;
    "ChartName": string;
    "ChartVersion": string;
    "AppVersion": string;
    "Description": string;
    "DeployedAt": time$0.Time;

    /** Creates a new Revision instance. */
    constructor($$source: Partial<Revision> = {}) {
        if (!("Number" in $$source)) {
            this["Number"] = 0;
        }
        if (!("Status" in $$source)) {
            this["Status"] = "";
        }
        if (!("ChartName" in $$source)) {
            this["ChartName"] = "";
        }
        if (!("ChartVersion" in $$source)) {
            this["ChartVersion"] = "";
        }
        if (!("AppVersion" in $$source)) {
            this["AppVersion"] = "";
        }
        if (!("Description" in $$source)) {
            this["Description"] = "";
        }
        if (!("DeployedAt" in $$source)) {
            this["DeployedAt"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Revision instance from a string or object.
     */
    static createFrom($$source: any = {}): Revision {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Revision($$parsedSource as Partial<Revision>);
    }
}

/**
 * RevisionDiff carries the three textual diffs surfaced to the UI.
 */
export class RevisionDiff {
    "Values": string;
    "ComputedValues": string;
    "Manifest": string;

    /** Creates a new RevisionDiff instance. */
    constructor($$source: Partial<RevisionDiff> = {}) {
        if (!("Values" in $$source)) {
            this["Values"] = "";
        }
        if (!("ComputedValues" in $$source)) {
            this["ComputedValues"] = "";
        }
        if (!("Manifest" in $$source)) {
            this["Manifest"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new RevisionDiff instance from a string or object.
     */
    static createFrom($$source: any = {}): RevisionDiff {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new RevisionDiff($$parsedSource as Partial<RevisionDiff>);
    }
}

/**
 * TestResult is returned from a synchronous helm-test run.
 */
export class TestResult {
    "Phase": string;
    "Logs": string;

    /** Creates a new TestResult instance. */
    constructor($$source: Partial<TestResult> = {}) {
        if (!("Phase" in $$source)) {
            this["Phase"] = "";
        }
        if (!("Logs" in $$source)) {
            this["Logs"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TestResult instance from a string or object.
     */
    static createFrom($$source: any = {}): TestResult {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new TestResult($$parsedSource as Partial<TestResult>);
    }
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
