// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class CommandEntry {
    "pluginName": string;
    "id": string;
    "label": string;
    "icon"?: string | null;
    "component"?: string | null;
    "perms": PermsSummary;

    /** Creates a new CommandEntry instance. */
    constructor($$source: Partial<CommandEntry> = {}) {
        if (!("pluginName" in $$source)) {
            this["pluginName"] = "";
        }
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("label" in $$source)) {
            this["label"] = "";
        }
        if (!("perms" in $$source)) {
            this["perms"] = (new PermsSummary());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CommandEntry instance from a string or object.
     */
    static createFrom($$source: any = {}): CommandEntry {
        const $$createField5_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("perms" in $$parsedSource) {
            $$parsedSource["perms"] = $$createField5_0($$parsedSource["perms"]);
        }
        return new CommandEntry($$parsedSource as Partial<CommandEntry>);
    }
}

export class ContextMenuEntry {
    "pluginName": string;
    "gvr": string;
    "id": string;
    "label": string;
    "component": string;

    /** Creates a new ContextMenuEntry instance. */
    constructor($$source: Partial<ContextMenuEntry> = {}) {
        if (!("pluginName" in $$source)) {
            this["pluginName"] = "";
        }
        if (!("gvr" in $$source)) {
            this["gvr"] = "";
        }
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("label" in $$source)) {
            this["label"] = "";
        }
        if (!("component" in $$source)) {
            this["component"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ContextMenuEntry instance from a string or object.
     */
    static createFrom($$source: any = {}): ContextMenuEntry {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ContextMenuEntry($$parsedSource as Partial<ContextMenuEntry>);
    }
}

export class DetailTabEntry {
    "pluginName": string;
    "gvr": string;
    "id": string;
    "label": string;
    "component": string;
    "perms": PermsSummary;

    /** Creates a new DetailTabEntry instance. */
    constructor($$source: Partial<DetailTabEntry> = {}) {
        if (!("pluginName" in $$source)) {
            this["pluginName"] = "";
        }
        if (!("gvr" in $$source)) {
            this["gvr"] = "";
        }
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("label" in $$source)) {
            this["label"] = "";
        }
        if (!("component" in $$source)) {
            this["component"] = "";
        }
        if (!("perms" in $$source)) {
            this["perms"] = (new PermsSummary());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DetailTabEntry instance from a string or object.
     */
    static createFrom($$source: any = {}): DetailTabEntry {
        const $$createField5_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("perms" in $$parsedSource) {
            $$parsedSource["perms"] = $$createField5_0($$parsedSource["perms"]);
        }
        return new DetailTabEntry($$parsedSource as Partial<DetailTabEntry>);
    }
}

export class HeaderWidgetEntry {
    "pluginName": string;
    "id": string;
    "component": string;

    /** Creates a new HeaderWidgetEntry instance. */
    constructor($$source: Partial<HeaderWidgetEntry> = {}) {
        if (!("pluginName" in $$source)) {
            this["pluginName"] = "";
        }
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("component" in $$source)) {
            this["component"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new HeaderWidgetEntry instance from a string or object.
     */
    static createFrom($$source: any = {}): HeaderWidgetEntry {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new HeaderWidgetEntry($$parsedSource as Partial<HeaderWidgetEntry>);
    }
}

export class ListColumnEntry {
    "pluginName": string;
    "gvr": string;
    "id": string;
    "label": string;
    "component": string;

    /** Creates a new ListColumnEntry instance. */
    constructor($$source: Partial<ListColumnEntry> = {}) {
        if (!("pluginName" in $$source)) {
            this["pluginName"] = "";
        }
        if (!("gvr" in $$source)) {
            this["gvr"] = "";
        }
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("label" in $$source)) {
            this["label"] = "";
        }
        if (!("component" in $$source)) {
            this["component"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ListColumnEntry instance from a string or object.
     */
    static createFrom($$source: any = {}): ListColumnEntry {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ListColumnEntry($$parsedSource as Partial<ListColumnEntry>);
    }
}

export class MetricQueryEntry {
    "pluginName": string;
    "gvr": string;
    "name": string;
    "query": string;
    "unit": string;

    /** Creates a new MetricQueryEntry instance. */
    constructor($$source: Partial<MetricQueryEntry> = {}) {
        if (!("pluginName" in $$source)) {
            this["pluginName"] = "";
        }
        if (!("gvr" in $$source)) {
            this["gvr"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("query" in $$source)) {
            this["query"] = "";
        }
        if (!("unit" in $$source)) {
            this["unit"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new MetricQueryEntry instance from a string or object.
     */
    static createFrom($$source: any = {}): MetricQueryEntry {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new MetricQueryEntry($$parsedSource as Partial<MetricQueryEntry>);
    }
}

export class OverviewFieldEntry {
    "pluginName": string;
    "gvr": string;
    "id": string;
    "label": string;
    "component": string;

    /** Creates a new OverviewFieldEntry instance. */
    constructor($$source: Partial<OverviewFieldEntry> = {}) {
        if (!("pluginName" in $$source)) {
            this["pluginName"] = "";
        }
        if (!("gvr" in $$source)) {
            this["gvr"] = "";
        }
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("label" in $$source)) {
            this["label"] = "";
        }
        if (!("component" in $$source)) {
            this["component"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new OverviewFieldEntry instance from a string or object.
     */
    static createFrom($$source: any = {}): OverviewFieldEntry {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new OverviewFieldEntry($$parsedSource as Partial<OverviewFieldEntry>);
    }
}

export class PermsSummary {
    "resources"?: ResourcePerm[];
    "logs"?: boolean;
    "exec"?: boolean;
    "storage"?: boolean;
    "events"?: boolean;
    "wasi"?: string[];

    /** Creates a new PermsSummary instance. */
    constructor($$source: Partial<PermsSummary> = {}) {

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PermsSummary instance from a string or object.
     */
    static createFrom($$source: any = {}): PermsSummary {
        const $$createField0_0 = $$createType2;
        const $$createField5_0 = $$createType3;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("resources" in $$parsedSource) {
            $$parsedSource["resources"] = $$createField0_0($$parsedSource["resources"]);
        }
        if ("wasi" in $$parsedSource) {
            $$parsedSource["wasi"] = $$createField5_0($$parsedSource["wasi"]);
        }
        return new PermsSummary($$parsedSource as Partial<PermsSummary>);
    }
}

export class PluginInfo {
    "name": string;
    "version": string;
    "displayName": string;
    "description"?: string;
    "status": string;
    "error"?: string;
    "conflictWarnings"?: string[];
    "dir": string;
    "permissions"?: PermsSummary | null;

    /** Creates a new PluginInfo instance. */
    constructor($$source: Partial<PluginInfo> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("version" in $$source)) {
            this["version"] = "";
        }
        if (!("displayName" in $$source)) {
            this["displayName"] = "";
        }
        if (!("status" in $$source)) {
            this["status"] = "";
        }
        if (!("dir" in $$source)) {
            this["dir"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PluginInfo instance from a string or object.
     */
    static createFrom($$source: any = {}): PluginInfo {
        const $$createField6_0 = $$createType3;
        const $$createField8_0 = $$createType4;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("conflictWarnings" in $$parsedSource) {
            $$parsedSource["conflictWarnings"] = $$createField6_0($$parsedSource["conflictWarnings"]);
        }
        if ("permissions" in $$parsedSource) {
            $$parsedSource["permissions"] = $$createField8_0($$parsedSource["permissions"]);
        }
        return new PluginInfo($$parsedSource as Partial<PluginInfo>);
    }
}

export class ResourcePerm {
    "group": string;
    "version": string;
    "resource": string;
    "verbs": string[];

    /** Creates a new ResourcePerm instance. */
    constructor($$source: Partial<ResourcePerm> = {}) {
        if (!("group" in $$source)) {
            this["group"] = "";
        }
        if (!("version" in $$source)) {
            this["version"] = "";
        }
        if (!("resource" in $$source)) {
            this["resource"] = "";
        }
        if (!("verbs" in $$source)) {
            this["verbs"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ResourcePerm instance from a string or object.
     */
    static createFrom($$source: any = {}): ResourcePerm {
        const $$createField3_0 = $$createType3;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("verbs" in $$parsedSource) {
            $$parsedSource["verbs"] = $$createField3_0($$parsedSource["verbs"]);
        }
        return new ResourcePerm($$parsedSource as Partial<ResourcePerm>);
    }
}

export class SidebarEntry {
    "category": string;
    "label": string;
    "gvr": string;
    "icon"?: string;
    "plugin": string;

    /** Creates a new SidebarEntry instance. */
    constructor($$source: Partial<SidebarEntry> = {}) {
        if (!("category" in $$source)) {
            this["category"] = "";
        }
        if (!("label" in $$source)) {
            this["label"] = "";
        }
        if (!("gvr" in $$source)) {
            this["gvr"] = "";
        }
        if (!("plugin" in $$source)) {
            this["plugin"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SidebarEntry instance from a string or object.
     */
    static createFrom($$source: any = {}): SidebarEntry {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SidebarEntry($$parsedSource as Partial<SidebarEntry>);
    }
}

export class StatusBarEntry {
    "pluginName": string;
    "id": string;
    "component": string;

    /** Creates a new StatusBarEntry instance. */
    constructor($$source: Partial<StatusBarEntry> = {}) {
        if (!("pluginName" in $$source)) {
            this["pluginName"] = "";
        }
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("component" in $$source)) {
            this["component"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new StatusBarEntry instance from a string or object.
     */
    static createFrom($$source: any = {}): StatusBarEntry {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new StatusBarEntry($$parsedSource as Partial<StatusBarEntry>);
    }
}

// Private type creation functions
const $$createType0 = PermsSummary.createFrom;
const $$createType1 = ResourcePerm.createFrom;
const $$createType2 = $Create.Array($$createType1);
const $$createType3 = $Create.Array($Create.Any);
const $$createType4 = $Create.Nullable($$createType0);
