// @ts-nocheck
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class StreamingConfig {
    /**
     * Creates a new StreamingConfig instance.
     * @param {Partial<StreamingConfig>} [$$source = {}] - The source object to create the StreamingConfig.
     */
    constructor($$source = {}) {
        if (!("port" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["port"] = 0;
        }
        if (!("token" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["token"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new StreamingConfig instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {StreamingConfig}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new StreamingConfig(/** @type {Partial<StreamingConfig>} */($$parsedSource));
    }
}
