// @ts-nocheck
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as time$0 from "../../../../../time/models.js";

/**
 * APIResource describes a discoverable resource on the cluster, including
 * optional metadata useful for rendering (printer columns, subresources,
 * scale subresource paths for CRDs).
 */
export class APIResource {
    /**
     * Creates a new APIResource instance.
     * @param {Partial<APIResource>} [$$source = {}] - The source object to create the APIResource.
     */
    constructor($$source = {}) {
        if (!("gvr" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["gvr"] = "";
        }
        if (!("kind" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["kind"] = "";
        }
        if (!("namespaced" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["namespaced"] = false;
        }
        if (!("subresources" in $$source)) {
            /**
             * @member
             * @type {ResourceSubresources}
             */
            this["subresources"] = (new ResourceSubresources());
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {AdditionalPrinterColumn[] | undefined}
             */
            this["printerColumns"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {ScaleSubresourceSpec | null | undefined}
             */
            this["scaleSpec"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new APIResource instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {APIResource}
     */
    static createFrom($$source = {}) {
        const $$createField3_0 = $$createType0;
        const $$createField4_0 = $$createType2;
        const $$createField5_0 = $$createType4;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("subresources" in $$parsedSource) {
            $$parsedSource["subresources"] = $$createField3_0($$parsedSource["subresources"]);
        }
        if ("printerColumns" in $$parsedSource) {
            $$parsedSource["printerColumns"] = $$createField4_0($$parsedSource["printerColumns"]);
        }
        if ("scaleSpec" in $$parsedSource) {
            $$parsedSource["scaleSpec"] = $$createField5_0($$parsedSource["scaleSpec"]);
        }
        return new APIResource(/** @type {Partial<APIResource>} */($$parsedSource));
    }
}

export class APIServerHealth {
    /**
     * Creates a new APIServerHealth instance.
     * @param {Partial<APIServerHealth>} [$$source = {}] - The source object to create the APIServerHealth.
     */
    constructor($$source = {}) {
        if (!("livez" in $$source)) {
            /**
             * @member
             * @type {HealthStatus}
             */
            this["livez"] = HealthStatus.$zero;
        }
        if (!("readyz" in $$source)) {
            /**
             * @member
             * @type {HealthStatus}
             */
            this["readyz"] = HealthStatus.$zero;
        }
        if (!("healthz" in $$source)) {
            /**
             * @member
             * @type {HealthStatus}
             */
            this["healthz"] = HealthStatus.$zero;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new APIServerHealth instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {APIServerHealth}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new APIServerHealth(/** @type {Partial<APIServerHealth>} */($$parsedSource));
    }
}

/**
 * AdditionalPrinterColumn mirrors the CRD printer column definition used by
 * kubectl's column rendering.
 */
export class AdditionalPrinterColumn {
    /**
     * Creates a new AdditionalPrinterColumn instance.
     * @param {Partial<AdditionalPrinterColumn>} [$$source = {}] - The source object to create the AdditionalPrinterColumn.
     */
    constructor($$source = {}) {
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("type" in $$source)) {
            /**
             * "string" | "integer" | "number" | "boolean" | "date"
             * @member
             * @type {string}
             */
            this["type"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["format"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["description"] = undefined;
        }
        if (!("priority" in $$source)) {
            /**
             * 0 = visible by default
             * @member
             * @type {number}
             */
            this["priority"] = 0;
        }
        if (!("jsonPath" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["jsonPath"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AdditionalPrinterColumn instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {AdditionalPrinterColumn}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new AdditionalPrinterColumn(/** @type {Partial<AdditionalPrinterColumn>} */($$parsedSource));
    }
}

export class ClusterHealth {
    /**
     * Creates a new ClusterHealth instance.
     * @param {Partial<ClusterHealth>} [$$source = {}] - The source object to create the ClusterHealth.
     */
    constructor($$source = {}) {
        if (!("apiServer" in $$source)) {
            /**
             * @member
             * @type {APIServerHealth}
             */
            this["apiServer"] = (new APIServerHealth());
        }
        if (!("components" in $$source)) {
            /**
             * @member
             * @type {ComponentHealth[]}
             */
            this["components"] = [];
        }
        if (!("nodes" in $$source)) {
            /**
             * @member
             * @type {NodeSummary}
             */
            this["nodes"] = (new NodeSummary());
        }
        if (!("checkedAt" in $$source)) {
            /**
             * @member
             * @type {time$0.Time}
             */
            this["checkedAt"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ClusterHealth instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ClusterHealth}
     */
    static createFrom($$source = {}) {
        const $$createField0_0 = $$createType5;
        const $$createField1_0 = $$createType7;
        const $$createField2_0 = $$createType8;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("apiServer" in $$parsedSource) {
            $$parsedSource["apiServer"] = $$createField0_0($$parsedSource["apiServer"]);
        }
        if ("components" in $$parsedSource) {
            $$parsedSource["components"] = $$createField1_0($$parsedSource["components"]);
        }
        if ("nodes" in $$parsedSource) {
            $$parsedSource["nodes"] = $$createField2_0($$parsedSource["nodes"]);
        }
        return new ClusterHealth(/** @type {Partial<ClusterHealth>} */($$parsedSource));
    }
}

export class ComponentHealth {
    /**
     * Creates a new ComponentHealth instance.
     * @param {Partial<ComponentHealth>} [$$source = {}] - The source object to create the ComponentHealth.
     */
    constructor($$source = {}) {
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("status" in $$source)) {
            /**
             * @member
             * @type {HealthStatus}
             */
            this["status"] = HealthStatus.$zero;
        }
        if (!("message" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["message"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ComponentHealth instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ComponentHealth}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ComponentHealth(/** @type {Partial<ComponentHealth>} */($$parsedSource));
    }
}

/**
 * @readonly
 * @enum {number}
 */
export const ConnectionStatus = {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero: 0,

    StatusDisconnected: 0,
    StatusConnecting: 1,
    StatusConnected: 2,
    StatusError: 3,
};

/**
 * @readonly
 * @enum {number}
 */
export const HealthStatus = {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero: 0,

    HealthOK: 0,
    HealthDegraded: 1,
    HealthUnknown: 2,
};

export class KubeContext {
    /**
     * Creates a new KubeContext instance.
     * @param {Partial<KubeContext>} [$$source = {}] - The source object to create the KubeContext.
     */
    constructor($$source = {}) {
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("cluster" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["cluster"] = "";
        }
        if (!("user" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["user"] = "";
        }
        if (!("namespace" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["namespace"] = "";
        }
        if (!("status" in $$source)) {
            /**
             * @member
             * @type {ConnectionStatus}
             */
            this["status"] = ConnectionStatus.$zero;
        }
        if (!("serverVersion" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["serverVersion"] = "";
        }
        if (!("provider" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["provider"] = "";
        }
        if (!("sourcePath" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["sourcePath"] = "";
        }
        if (!("isDefault" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["isDefault"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new KubeContext instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {KubeContext}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new KubeContext(/** @type {Partial<KubeContext>} */($$parsedSource));
    }
}

export class Manager {
    /**
     * Creates a new Manager instance.
     * @param {Partial<Manager>} [$$source = {}] - The source object to create the Manager.
     */
    constructor($$source = {}) {

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Manager instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Manager}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Manager(/** @type {Partial<Manager>} */($$parsedSource));
    }
}

export class NodeSummary {
    /**
     * Creates a new NodeSummary instance.
     * @param {Partial<NodeSummary>} [$$source = {}] - The source object to create the NodeSummary.
     */
    constructor($$source = {}) {
        if (!("total" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["total"] = 0;
        }
        if (!("ready" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["ready"] = 0;
        }
        if (!("notReady" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["notReady"] = 0;
        }
        if (!("schedulingDisabled" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["schedulingDisabled"] = 0;
        }
        if (!("permissionDenied" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["permissionDenied"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new NodeSummary instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {NodeSummary}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new NodeSummary(/** @type {Partial<NodeSummary>} */($$parsedSource));
    }
}

/**
 * ResourceSubresources captures which well-known subresources are supported.
 */
export class ResourceSubresources {
    /**
     * Creates a new ResourceSubresources instance.
     * @param {Partial<ResourceSubresources>} [$$source = {}] - The source object to create the ResourceSubresources.
     */
    constructor($$source = {}) {
        if (!("scale" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["scale"] = false;
        }
        if (!("status" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["status"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ResourceSubresources instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ResourceSubresources}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ResourceSubresources(/** @type {Partial<ResourceSubresources>} */($$parsedSource));
    }
}

/**
 * ScaleSubresourceSpec captures the paths the CRD declared for its scale
 * subresource. Defaults are "spec.replicas" / "status.replicas".
 */
export class ScaleSubresourceSpec {
    /**
     * Creates a new ScaleSubresourceSpec instance.
     * @param {Partial<ScaleSubresourceSpec>} [$$source = {}] - The source object to create the ScaleSubresourceSpec.
     */
    constructor($$source = {}) {
        if (!("specReplicasPath" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["specReplicasPath"] = "";
        }
        if (!("statusReplicasPath" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["statusReplicasPath"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ScaleSubresourceSpec instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ScaleSubresourceSpec}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ScaleSubresourceSpec(/** @type {Partial<ScaleSubresourceSpec>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = ResourceSubresources.createFrom;
const $$createType1 = AdditionalPrinterColumn.createFrom;
const $$createType2 = $Create.Array($$createType1);
const $$createType3 = ScaleSubresourceSpec.createFrom;
const $$createType4 = $Create.Nullable($$createType3);
const $$createType5 = APIServerHealth.createFrom;
const $$createType6 = ComponentHealth.createFrom;
const $$createType7 = $Create.Array($$createType6);
const $$createType8 = NodeSummary.createFrom;
