// @ts-nocheck
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class CommandEntry {
    /**
     * Creates a new CommandEntry instance.
     * @param {Partial<CommandEntry>} [$$source = {}] - The source object to create the CommandEntry.
     */
    constructor($$source = {}) {
        if (!("pluginName" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["pluginName"] = "";
        }
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("label" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["label"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | null | undefined}
             */
            this["icon"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | null | undefined}
             */
            this["component"] = undefined;
        }
        if (!("perms" in $$source)) {
            /**
             * @member
             * @type {PermsSummary}
             */
            this["perms"] = (new PermsSummary());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CommandEntry instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {CommandEntry}
     */
    static createFrom($$source = {}) {
        const $$createField5_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("perms" in $$parsedSource) {
            $$parsedSource["perms"] = $$createField5_0($$parsedSource["perms"]);
        }
        return new CommandEntry(/** @type {Partial<CommandEntry>} */($$parsedSource));
    }
}

export class ContextMenuEntry {
    /**
     * Creates a new ContextMenuEntry instance.
     * @param {Partial<ContextMenuEntry>} [$$source = {}] - The source object to create the ContextMenuEntry.
     */
    constructor($$source = {}) {
        if (!("pluginName" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["pluginName"] = "";
        }
        if (!("gvr" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["gvr"] = "";
        }
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("label" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["label"] = "";
        }
        if (!("component" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["component"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ContextMenuEntry instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ContextMenuEntry}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ContextMenuEntry(/** @type {Partial<ContextMenuEntry>} */($$parsedSource));
    }
}

export class DetailTabEntry {
    /**
     * Creates a new DetailTabEntry instance.
     * @param {Partial<DetailTabEntry>} [$$source = {}] - The source object to create the DetailTabEntry.
     */
    constructor($$source = {}) {
        if (!("pluginName" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["pluginName"] = "";
        }
        if (!("gvr" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["gvr"] = "";
        }
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("label" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["label"] = "";
        }
        if (!("component" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["component"] = "";
        }
        if (!("perms" in $$source)) {
            /**
             * @member
             * @type {PermsSummary}
             */
            this["perms"] = (new PermsSummary());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DetailTabEntry instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {DetailTabEntry}
     */
    static createFrom($$source = {}) {
        const $$createField5_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("perms" in $$parsedSource) {
            $$parsedSource["perms"] = $$createField5_0($$parsedSource["perms"]);
        }
        return new DetailTabEntry(/** @type {Partial<DetailTabEntry>} */($$parsedSource));
    }
}

export class HeaderWidgetEntry {
    /**
     * Creates a new HeaderWidgetEntry instance.
     * @param {Partial<HeaderWidgetEntry>} [$$source = {}] - The source object to create the HeaderWidgetEntry.
     */
    constructor($$source = {}) {
        if (!("pluginName" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["pluginName"] = "";
        }
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("component" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["component"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new HeaderWidgetEntry instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {HeaderWidgetEntry}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new HeaderWidgetEntry(/** @type {Partial<HeaderWidgetEntry>} */($$parsedSource));
    }
}

export class ListColumnEntry {
    /**
     * Creates a new ListColumnEntry instance.
     * @param {Partial<ListColumnEntry>} [$$source = {}] - The source object to create the ListColumnEntry.
     */
    constructor($$source = {}) {
        if (!("pluginName" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["pluginName"] = "";
        }
        if (!("gvr" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["gvr"] = "";
        }
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("label" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["label"] = "";
        }
        if (!("component" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["component"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ListColumnEntry instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ListColumnEntry}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ListColumnEntry(/** @type {Partial<ListColumnEntry>} */($$parsedSource));
    }
}

export class MetricQueryEntry {
    /**
     * Creates a new MetricQueryEntry instance.
     * @param {Partial<MetricQueryEntry>} [$$source = {}] - The source object to create the MetricQueryEntry.
     */
    constructor($$source = {}) {
        if (!("pluginName" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["pluginName"] = "";
        }
        if (!("gvr" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["gvr"] = "";
        }
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("query" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["query"] = "";
        }
        if (!("unit" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["unit"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new MetricQueryEntry instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {MetricQueryEntry}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new MetricQueryEntry(/** @type {Partial<MetricQueryEntry>} */($$parsedSource));
    }
}

export class OverviewFieldEntry {
    /**
     * Creates a new OverviewFieldEntry instance.
     * @param {Partial<OverviewFieldEntry>} [$$source = {}] - The source object to create the OverviewFieldEntry.
     */
    constructor($$source = {}) {
        if (!("pluginName" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["pluginName"] = "";
        }
        if (!("gvr" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["gvr"] = "";
        }
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("label" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["label"] = "";
        }
        if (!("component" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["component"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new OverviewFieldEntry instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {OverviewFieldEntry}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new OverviewFieldEntry(/** @type {Partial<OverviewFieldEntry>} */($$parsedSource));
    }
}

export class PermsSummary {
    /**
     * Creates a new PermsSummary instance.
     * @param {Partial<PermsSummary>} [$$source = {}] - The source object to create the PermsSummary.
     */
    constructor($$source = {}) {
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {ResourcePerm[] | undefined}
             */
            this["resources"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {boolean | undefined}
             */
            this["logs"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {boolean | undefined}
             */
            this["exec"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {boolean | undefined}
             */
            this["storage"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {boolean | undefined}
             */
            this["events"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string[] | undefined}
             */
            this["wasi"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PermsSummary instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {PermsSummary}
     */
    static createFrom($$source = {}) {
        const $$createField0_0 = $$createType2;
        const $$createField5_0 = $$createType3;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("resources" in $$parsedSource) {
            $$parsedSource["resources"] = $$createField0_0($$parsedSource["resources"]);
        }
        if ("wasi" in $$parsedSource) {
            $$parsedSource["wasi"] = $$createField5_0($$parsedSource["wasi"]);
        }
        return new PermsSummary(/** @type {Partial<PermsSummary>} */($$parsedSource));
    }
}

export class PluginInfo {
    /**
     * Creates a new PluginInfo instance.
     * @param {Partial<PluginInfo>} [$$source = {}] - The source object to create the PluginInfo.
     */
    constructor($$source = {}) {
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("version" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["version"] = "";
        }
        if (!("displayName" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["displayName"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["description"] = undefined;
        }
        if (!("status" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["status"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["error"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string[] | undefined}
             */
            this["conflictWarnings"] = undefined;
        }
        if (!("dir" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["dir"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {PermsSummary | null | undefined}
             */
            this["permissions"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PluginInfo instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {PluginInfo}
     */
    static createFrom($$source = {}) {
        const $$createField6_0 = $$createType3;
        const $$createField8_0 = $$createType4;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("conflictWarnings" in $$parsedSource) {
            $$parsedSource["conflictWarnings"] = $$createField6_0($$parsedSource["conflictWarnings"]);
        }
        if ("permissions" in $$parsedSource) {
            $$parsedSource["permissions"] = $$createField8_0($$parsedSource["permissions"]);
        }
        return new PluginInfo(/** @type {Partial<PluginInfo>} */($$parsedSource));
    }
}

export class ResourcePerm {
    /**
     * Creates a new ResourcePerm instance.
     * @param {Partial<ResourcePerm>} [$$source = {}] - The source object to create the ResourcePerm.
     */
    constructor($$source = {}) {
        if (!("group" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["group"] = "";
        }
        if (!("version" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["version"] = "";
        }
        if (!("resource" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["resource"] = "";
        }
        if (!("verbs" in $$source)) {
            /**
             * @member
             * @type {string[]}
             */
            this["verbs"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ResourcePerm instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ResourcePerm}
     */
    static createFrom($$source = {}) {
        const $$createField3_0 = $$createType3;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("verbs" in $$parsedSource) {
            $$parsedSource["verbs"] = $$createField3_0($$parsedSource["verbs"]);
        }
        return new ResourcePerm(/** @type {Partial<ResourcePerm>} */($$parsedSource));
    }
}

export class SidebarEntry {
    /**
     * Creates a new SidebarEntry instance.
     * @param {Partial<SidebarEntry>} [$$source = {}] - The source object to create the SidebarEntry.
     */
    constructor($$source = {}) {
        if (!("category" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["category"] = "";
        }
        if (!("label" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["label"] = "";
        }
        if (!("gvr" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["gvr"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["icon"] = undefined;
        }
        if (!("plugin" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["plugin"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SidebarEntry instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {SidebarEntry}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SidebarEntry(/** @type {Partial<SidebarEntry>} */($$parsedSource));
    }
}

export class StatusBarEntry {
    /**
     * Creates a new StatusBarEntry instance.
     * @param {Partial<StatusBarEntry>} [$$source = {}] - The source object to create the StatusBarEntry.
     */
    constructor($$source = {}) {
        if (!("pluginName" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["pluginName"] = "";
        }
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("component" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["component"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new StatusBarEntry instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {StatusBarEntry}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new StatusBarEntry(/** @type {Partial<StatusBarEntry>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = PermsSummary.createFrom;
const $$createType1 = ResourcePerm.createFrom;
const $$createType2 = $Create.Array($$createType1);
const $$createType3 = $Create.Array($Create.Any);
const $$createType4 = $Create.Nullable($$createType0);
