// @ts-nocheck
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class Session {
    /**
     * Creates a new Session instance.
     * @param {Partial<Session>} [$$source = {}] - The source object to create the Session.
     */
    constructor($$source = {}) {
        if (!("connectedClusters" in $$source)) {
            /**
             * @member
             * @type {string[]}
             */
            this["connectedClusters"] = [];
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["lastActiveContext"] = undefined;
        }
        if (!("activeNamespaces" in $$source)) {
            /**
             * @member
             * @type {{ [_ in string]?: string }}
             */
            this["activeNamespaces"] = {};
        }
        if (!("openTabs" in $$source)) {
            /**
             * @member
             * @type {TabState[]}
             */
            this["openTabs"] = [];
        }
        if (!("activeTab" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["activeTab"] = 0;
        }
        if (!("sidebarCollapsed" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["sidebarCollapsed"] = false;
        }
        if (!("terminalFontSize" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["terminalFontSize"] = 0;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {number | undefined}
             */
            this["sidebarWidth"] = undefined;
        }
        if (!("window" in $$source)) {
            /**
             * @member
             * @type {WindowState}
             */
            this["window"] = (new WindowState());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Session instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Session}
     */
    static createFrom($$source = {}) {
        const $$createField0_0 = $$createType0;
        const $$createField2_0 = $$createType1;
        const $$createField3_0 = $$createType3;
        const $$createField8_0 = $$createType4;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("connectedClusters" in $$parsedSource) {
            $$parsedSource["connectedClusters"] = $$createField0_0($$parsedSource["connectedClusters"]);
        }
        if ("activeNamespaces" in $$parsedSource) {
            $$parsedSource["activeNamespaces"] = $$createField2_0($$parsedSource["activeNamespaces"]);
        }
        if ("openTabs" in $$parsedSource) {
            $$parsedSource["openTabs"] = $$createField3_0($$parsedSource["openTabs"]);
        }
        if ("window" in $$parsedSource) {
            $$parsedSource["window"] = $$createField8_0($$parsedSource["window"]);
        }
        return new Session(/** @type {Partial<Session>} */($$parsedSource));
    }
}

export class TabState {
    /**
     * Creates a new TabState instance.
     * @param {Partial<TabState>} [$$source = {}] - The source object to create the TabState.
     */
    constructor($$source = {}) {
        if (!("clusterContext" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["clusterContext"] = "";
        }
        if (!("gvr" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["gvr"] = "";
        }
        if (!("namespace" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["namespace"] = "";
        }
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {number | undefined}
             */
            this["scrollPosition"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TabState instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {TabState}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new TabState(/** @type {Partial<TabState>} */($$parsedSource));
    }
}

export class WindowState {
    /**
     * Creates a new WindowState instance.
     * @param {Partial<WindowState>} [$$source = {}] - The source object to create the WindowState.
     */
    constructor($$source = {}) {
        if (!("x" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["x"] = 0;
        }
        if (!("y" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["y"] = 0;
        }
        if (!("width" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["width"] = 0;
        }
        if (!("height" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["height"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new WindowState instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {WindowState}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new WindowState(/** @type {Partial<WindowState>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
const $$createType1 = $Create.Map($Create.Any, $Create.Any);
const $$createType2 = TabState.createFrom;
const $$createType3 = $Create.Array($$createType2);
const $$createType4 = WindowState.createFrom;
