// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as context$0 from "../../../../../context/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as cluster$0 from "../cluster/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as config$0 from "../config/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as exec$0 from "../exec/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as logs$0 from "../logs/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as portforward$0 from "../portforward/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as session$0 from "../session/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as streaming$0 from "../streaming/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as volumebrowser$0 from "../volumebrowser/models.js";

export function BrowseKubeconfigFile(): $CancellablePromise<string> {
    return $Call.ByID(3812723218);
}

export function BrowseManifestFile(): $CancellablePromise<string> {
    return $Call.ByID(1736414284);
}

export function BrowsePluginFile(): $CancellablePromise<string> {
    return $Call.ByID(3044813074);
}

export function ClusterManager(): $CancellablePromise<cluster$0.Manager | null> {
    return $Call.ByID(1018019196).then(($result: any) => {
        return $$createType1($result);
    });
}

export function Config(): $CancellablePromise<config$0.Config | null> {
    return $Call.ByID(2025854175).then(($result: any) => {
        return $$createType3($result);
    });
}

export function Ctx(): $CancellablePromise<context$0.Context> {
    return $Call.ByID(532202374);
}

export function ExecManager(): $CancellablePromise<exec$0.Manager | null> {
    return $Call.ByID(181455691).then(($result: any) => {
        return $$createType5($result);
    });
}

export function GetClusterHealth(connCtx: string): $CancellablePromise<cluster$0.ClusterHealth> {
    return $Call.ByID(3203745337, connCtx).then(($result: any) => {
        return $$createType6($result);
    });
}

export function GetSession(): $CancellablePromise<session$0.Session | null> {
    return $Call.ByID(3130725049).then(($result: any) => {
        return $$createType8($result);
    });
}

export function GetStreamingConfig(): $CancellablePromise<streaming$0.StreamingConfig> {
    return $Call.ByID(3228718747).then(($result: any) => {
        return $$createType9($result);
    });
}

export function LogFrontend(level: string, message: string, attrsJSON: string): $CancellablePromise<void> {
    return $Call.ByID(4188773513, level, message, attrsJSON);
}

export function LogStreamer(): $CancellablePromise<logs$0.Streamer | null> {
    return $Call.ByID(2788254666).then(($result: any) => {
        return $$createType11($result);
    });
}

export function PortForwardManager(): $CancellablePromise<portforward$0.Manager | null> {
    return $Call.ByID(3269944274).then(($result: any) => {
        return $$createType13($result);
    });
}

export function RegisterPluginsDir(dir: string): $CancellablePromise<void> {
    return $Call.ByID(1267291503, dir);
}

export function SaveUIState(openTabs: session$0.TabState[], activeTab: number, sidebarCollapsed: boolean, terminalFontSize: number, sidebarWidth: number): $CancellablePromise<void> {
    return $Call.ByID(1357217799, openTabs, activeTab, sidebarCollapsed, terminalFontSize, sidebarWidth);
}

export function SetLastActiveContext(name: string): $CancellablePromise<void> {
    return $Call.ByID(312818588, name);
}

export function SetReadOnly(enabled: boolean): $CancellablePromise<void> {
    return $Call.ByID(1908353457, enabled);
}

export function VolumeBrowserManager(): $CancellablePromise<volumebrowser$0.Manager | null> {
    return $Call.ByID(1858241892).then(($result: any) => {
        return $$createType15($result);
    });
}

// Private type creation functions
const $$createType0 = cluster$0.Manager.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = config$0.Config.createFrom;
const $$createType3 = $Create.Nullable($$createType2);
const $$createType4 = exec$0.Manager.createFrom;
const $$createType5 = $Create.Nullable($$createType4);
const $$createType6 = cluster$0.ClusterHealth.createFrom;
const $$createType7 = session$0.Session.createFrom;
const $$createType8 = $Create.Nullable($$createType7);
const $$createType9 = streaming$0.StreamingConfig.createFrom;
const $$createType10 = logs$0.Streamer.createFrom;
const $$createType11 = $Create.Nullable($$createType10);
const $$createType12 = portforward$0.Manager.createFrom;
const $$createType13 = $Create.Nullable($$createType12);
const $$createType14 = volumebrowser$0.Manager.createFrom;
const $$createType15 = $Create.Nullable($$createType14);
