// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as cluster$0 from "../cluster/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function Activate(contextName: string): $CancellablePromise<void> {
    return $Call.ByID(1916362053, contextName);
}

export function AddKubeconfigPath(path: string): $CancellablePromise<cluster$0.KubeContext[]> {
    return $Call.ByID(3424427683, path).then(($result: any) => {
        return $$createType1($result);
    });
}

export function Connect(contextName: string): $CancellablePromise<void> {
    return $Call.ByID(2564928362, contextName);
}

export function CreateNamespace(contextName: string, name: string): $CancellablePromise<void> {
    return $Call.ByID(3190336079, contextName, name);
}

export function Deactivate(contextName: string): $CancellablePromise<void> {
    return $Call.ByID(1785056746, contextName);
}

export function DeleteNamespace(contextName: string, name: string): $CancellablePromise<void> {
    return $Call.ByID(3734241090, contextName, name);
}

export function Disconnect(contextName: string): $CancellablePromise<void> {
    return $Call.ByID(3294121038, contextName);
}

export function GetActiveNamespace(contextName: string): $CancellablePromise<string> {
    return $Call.ByID(3979351489, contextName);
}

export function GetClusterInfo(ctxName: string): $CancellablePromise<$models.ClusterInfo> {
    return $Call.ByID(3337850666, ctxName).then(($result: any) => {
        return $$createType2($result);
    });
}

export function GetStatus(contextName: string): $CancellablePromise<cluster$0.ConnectionStatus> {
    return $Call.ByID(3771597842, contextName);
}

export function ImportKubeconfigContent(content: string): $CancellablePromise<cluster$0.KubeContext[]> {
    return $Call.ByID(3631082547, content).then(($result: any) => {
        return $$createType1($result);
    });
}

export function ListContexts(): $CancellablePromise<cluster$0.KubeContext[]> {
    return $Call.ByID(1707520196).then(($result: any) => {
        return $$createType1($result);
    });
}

export function ListNamespaces(contextName: string): $CancellablePromise<string[]> {
    return $Call.ByID(1900087040, contextName).then(($result: any) => {
        return $$createType3($result);
    });
}

export function RemoveKubeconfigPath(path: string): $CancellablePromise<cluster$0.KubeContext[]> {
    return $Call.ByID(842984052, path).then(($result: any) => {
        return $$createType1($result);
    });
}

export function SwitchNamespace(contextName: string, $namespace: string): $CancellablePromise<void> {
    return $Call.ByID(4142974063, contextName, $namespace);
}

// Private type creation functions
const $$createType0 = cluster$0.KubeContext.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = $models.ClusterInfo.createFrom;
const $$createType3 = $Create.Array($Create.Any);
