// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as config$0 from "../config/models.js";

export function DeleteClusterPrefs(ctxName: string): $CancellablePromise<void> {
    return $Call.ByID(991424445, ctxName);
}

export function DeleteColumnPrefs(gvr: string): $CancellablePromise<void> {
    return $Call.ByID(4114770319, gvr);
}

export function GetClusterPrefs(ctxName: string): $CancellablePromise<config$0.ClusterPrefs | null> {
    return $Call.ByID(3907658678, ctxName).then(($result: any) => {
        return $$createType1($result);
    });
}

export function GetColumnPrefs(gvr: string): $CancellablePromise<config$0.GVRColumnPrefs | null> {
    return $Call.ByID(2172831658, gvr).then(($result: any) => {
        return $$createType3($result);
    });
}

export function GetCompactRows(): $CancellablePromise<boolean> {
    return $Call.ByID(2422269906);
}

export function GetConfig(): $CancellablePromise<config$0.Config | null> {
    return $Call.ByID(3349102092).then(($result: any) => {
        return $$createType5($result);
    });
}

export function GetInsecureSkipTLSVerify(): $CancellablePromise<boolean> {
    return $Call.ByID(3151101633);
}

export function GetResolvedPrefs(ctxName: string): $CancellablePromise<config$0.ResolvedPrefs> {
    return $Call.ByID(3736726204, ctxName).then(($result: any) => {
        return $$createType6($result);
    });
}

export function GetSavedFilters(gvr: string): $CancellablePromise<config$0.SavedFilter[]> {
    return $Call.ByID(2202435792, gvr).then(($result: any) => {
        return $$createType8($result);
    });
}

export function GetTerminalWebGL(): $CancellablePromise<boolean> {
    return $Call.ByID(1404868855);
}

export function GetTheme(): $CancellablePromise<string> {
    return $Call.ByID(3339073715);
}

export function ResetKeybindings(): $CancellablePromise<void> {
    return $Call.ByID(1736506518);
}

export function SetAccentColor(color: string): $CancellablePromise<void> {
    return $Call.ByID(2723403775, color);
}

export function SetClusterPrefs(ctxName: string, prefs: config$0.ClusterPrefs | null): $CancellablePromise<void> {
    return $Call.ByID(3679024642, ctxName, prefs);
}

export function SetClusterSavedFilters(ctxName: string, gvr: string, filters: config$0.SavedFilter[]): $CancellablePromise<void> {
    return $Call.ByID(3426066010, ctxName, gvr, filters);
}

export function SetColumnPrefs(gvr: string, prefs: config$0.GVRColumnPrefs | null): $CancellablePromise<void> {
    return $Call.ByID(2017648422, gvr, prefs);
}

export function SetCompactRows(compact: boolean): $CancellablePromise<void> {
    return $Call.ByID(407269070, compact);
}

export function SetContextualAutocomplete(enabled: boolean): $CancellablePromise<void> {
    return $Call.ByID(2277910361, enabled);
}

export function SetFontSize(size: number): $CancellablePromise<void> {
    return $Call.ByID(2949195894, size);
}

export function SetInsecureSkipTLSVerify(skip: boolean): $CancellablePromise<void> {
    return $Call.ByID(2704534973, skip);
}

export function SetKeybinding(actionID: string, keys: string): $CancellablePromise<void> {
    return $Call.ByID(644345986, actionID, keys);
}

export function SetSavedFilters(gvr: string, filters: config$0.SavedFilter[]): $CancellablePromise<void> {
    return $Call.ByID(3820903460, gvr, filters);
}

export function SetStartupBehavior(behavior: string, cluster: string): $CancellablePromise<void> {
    return $Call.ByID(3615998021, behavior, cluster);
}

export function SetTerminalWebGL(enabled: boolean): $CancellablePromise<void> {
    return $Call.ByID(95260947, enabled);
}

export function SetTheme(theme: string): $CancellablePromise<void> {
    return $Call.ByID(2227324903, theme);
}

export function SetVolumeBrowser(vb: config$0.VolumeBrowserConfig | null): $CancellablePromise<void> {
    return $Call.ByID(97409896, vb);
}

// Private type creation functions
const $$createType0 = config$0.ClusterPrefs.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = config$0.GVRColumnPrefs.createFrom;
const $$createType3 = $Create.Nullable($$createType2);
const $$createType4 = config$0.Config.createFrom;
const $$createType5 = $Create.Nullable($$createType4);
const $$createType6 = config$0.ResolvedPrefs.createFrom;
const $$createType7 = config$0.SavedFilter.createFrom;
const $$createType8 = $Create.Array($$createType7);
