// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

export function CancelDrain(contextName: string, nodeName: string): $CancellablePromise<void> {
    return $Call.ByID(575867988, contextName, nodeName);
}

/**
 * Cordon marks the node as unschedulable.
 */
export function CordonNode(contextName: string, nodeName: string): $CancellablePromise<void> {
    return $Call.ByID(2446363129, contextName, nodeName);
}

export function IsActive(contextName: string, nodeName: string): $CancellablePromise<boolean> {
    return $Call.ByID(2487772726, contextName, nodeName);
}

export function ListActive(contextName: string): $CancellablePromise<string[]> {
    return $Call.ByID(1665099622, contextName).then(($result: any) => {
        return $$createType0($result);
    });
}

export function StartDrain(contextName: string, nodeName: string): $CancellablePromise<void> {
    return $Call.ByID(474780626, contextName, nodeName);
}

/**
 * Uncordon marks the node as schedulable.
 */
export function UncordonNode(contextName: string, nodeName: string): $CancellablePromise<void> {
    return $Call.ByID(1142118830, contextName, nodeName);
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
