// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

export function CloseExecSession(sessionID: string): $CancellablePromise<void> {
    return $Call.ByID(234028266, sessionID);
}

export function OpenExecSession(ctxName: string, ns: string, podName: string, container: string, shell: string): $CancellablePromise<string> {
    return $Call.ByID(1841438172, ctxName, ns, podName, container, shell);
}
