// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * HelmService exposes Helm verbs and lazy detail-tab fetches over Wails RPC.
 * It owns the Helm backend, actions wrapper, and per-release SAR-gated calls.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as helm$0 from "../helm/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * CleanupTestPods deletes pods labelled as Helm test hooks for the given
 * release. Both the "helm.sh/hook=test-success" and "helm.sh/hook=test" labels
 * are recognised; the annotation form is not labelled and is not selectable
 * server-side, so we filter client-side by annotation as a fallback.
 */
export function CleanupTestPods(contextName: string, $namespace: string, releaseName: string): $CancellablePromise<void> {
    return $Call.ByID(3206390368, contextName, $namespace, releaseName);
}

export function DiffRevisions(contextName: string, $namespace: string, releaseName: string, $from: number, to: number): $CancellablePromise<helm$0.RevisionDiff> {
    return $Call.ByID(2689002639, contextName, $namespace, releaseName, $from, to).then(($result: any) => {
        return $$createType0($result);
    });
}

export function ForceDeleteReleaseSecret(contextName: string, $namespace: string, releaseName: string, revision: number): $CancellablePromise<void> {
    return $Call.ByID(1874861993, contextName, $namespace, releaseName, revision);
}

export function GetHistory(contextName: string, $namespace: string, releaseName: string): $CancellablePromise<helm$0.Revision[]> {
    return $Call.ByID(448915676, contextName, $namespace, releaseName).then(($result: any) => {
        return $$createType2($result);
    });
}

export function GetHooks(contextName: string, $namespace: string, releaseName: string, revision: number): $CancellablePromise<helm$0.Hook[]> {
    return $Call.ByID(3337667848, contextName, $namespace, releaseName, revision).then(($result: any) => {
        return $$createType4($result);
    });
}

export function GetManifest(contextName: string, $namespace: string, releaseName: string, revision: number): $CancellablePromise<string> {
    return $Call.ByID(1931393849, contextName, $namespace, releaseName, revision);
}

export function GetNotes(contextName: string, $namespace: string, releaseName: string, revision: number): $CancellablePromise<string> {
    return $Call.ByID(3306052593, contextName, $namespace, releaseName, revision);
}

export function GetOwnedResources(contextName: string, $namespace: string, releaseName: string, scanAll: boolean): $CancellablePromise<helm$0.OwnedRef[]> {
    return $Call.ByID(3286556010, contextName, $namespace, releaseName, scanAll).then(($result: any) => {
        return $$createType6($result);
    });
}

/**
 * GetReleasePermissions returns the per-verb RBAC allow flags for the
 * (context, namespace, release) triple. Errors from individual SAR calls
 * degrade gracefully: the specific verb is reported false but no error is
 * surfaced to the caller.
 */
export function GetReleasePermissions(contextName: string, $namespace: string, releaseName: string): $CancellablePromise<$models.HelmPermissions> {
    return $Call.ByID(1933921127, contextName, $namespace, releaseName).then(($result: any) => {
        return $$createType7($result);
    });
}

export function GetValues(contextName: string, $namespace: string, releaseName: string, computed: boolean, revision: number): $CancellablePromise<string> {
    return $Call.ByID(4076722466, contextName, $namespace, releaseName, computed, revision);
}

export function Rollback(contextName: string, $namespace: string, releaseName: string, revision: number, opts: $models.HelmRollbackOpts): $CancellablePromise<void> {
    return $Call.ByID(1703587940, contextName, $namespace, releaseName, revision, opts);
}

export function Test(contextName: string, $namespace: string, releaseName: string, opts: $models.HelmTestOpts): $CancellablePromise<helm$0.TestResult> {
    return $Call.ByID(742184180, contextName, $namespace, releaseName, opts).then(($result: any) => {
        return $$createType8($result);
    });
}

export function Uninstall(contextName: string, $namespace: string, releaseName: string, opts: $models.HelmUninstallOpts): $CancellablePromise<void> {
    return $Call.ByID(4281748658, contextName, $namespace, releaseName, opts);
}

// Private type creation functions
const $$createType0 = helm$0.RevisionDiff.createFrom;
const $$createType1 = helm$0.Revision.createFrom;
const $$createType2 = $Create.Array($$createType1);
const $$createType3 = helm$0.Hook.createFrom;
const $$createType4 = $Create.Array($$createType3);
const $$createType5 = helm$0.OwnedRef.createFrom;
const $$createType6 = $Create.Array($$createType5);
const $$createType7 = $models.HelmPermissions.createFrom;
const $$createType8 = helm$0.TestResult.createFrom;
