// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

import * as AppService from "./appservice.js";
import * as ClusterService from "./clusterservice.js";
import * as ConfigService from "./configservice.js";
import * as DrainService from "./drainservice.js";
import * as ExecService from "./execservice.js";
import * as HelmService from "./helmservice.js";
import * as LogService from "./logservice.js";
import * as MetricsService from "./metricsservice.js";
import * as PluginService from "./pluginservice.js";
import * as PortForwardService from "./portforwardservice.js";
import * as ResourceService from "./resourceservice.js";
import * as SchemaService from "./schemaservice.js";
import * as VolumeBrowserService from "./volumebrowserservice.js";
import * as WindowService from "./windowservice.js";
export {
    AppService,
    ClusterService,
    ConfigService,
    DrainService,
    ExecService,
    HelmService,
    LogService,
    MetricsService,
    PluginService,
    PortForwardService,
    ResourceService,
    SchemaService,
    VolumeBrowserService,
    WindowService
};

export {
    CapabilityState,
    ClusterInfo,
    HelmPermissions,
    HelmRollbackOpts,
    HelmTestOpts,
    HelmUninstallOpts,
    ListResult,
    ManagedPodDTO,
    OrphanPodDTO,
    RolloutRevision,
    SpawnOverridesDTO,
    SpawnRequestDTO,
    SpawnResult
} from "./models.js";
