// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as logs$0 from "../logs/models.js";

export function StartLogStream(ctxName: string, ns: string, podName: string, opts: logs$0.LogOptions): $CancellablePromise<string> {
    return $Call.ByID(475158610, ctxName, ns, podName, opts);
}

export function StopLogStream(streamID: string): $CancellablePromise<void> {
    return $Call.ByID(1299866654, streamID);
}
