// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as metrics$0 from "../metrics/models.js";

export function GetCapabilities(clusterCtx: string): $CancellablePromise<metrics$0.MetricsCapability> {
    return $Call.ByID(719665459, clusterCtx).then(($result: any) => {
        return $$createType0($result);
    });
}

export function GetListMetrics(clusterCtx: string, gvr: string, $namespace: string): $CancellablePromise<{ [_ in string]?: metrics$0.MetricResult[] }> {
    return $Call.ByID(496327662, clusterCtx, gvr, $namespace).then(($result: any) => {
        return $$createType3($result);
    });
}

export function GetNamespaceMetrics(clusterCtx: string, $namespace: string, rangeMinutes: number): $CancellablePromise<metrics$0.MetricsResponse | null> {
    return $Call.ByID(2982105593, clusterCtx, $namespace, rangeMinutes).then(($result: any) => {
        return $$createType5($result);
    });
}

export function GetPluginMetrics(clusterCtx: string, gvr: string, $namespace: string, name: string, rangeMinutes: number): $CancellablePromise<{ [_ in string]?: metrics$0.MetricResult[] }> {
    return $Call.ByID(1491496035, clusterCtx, gvr, $namespace, name, rangeMinutes).then(($result: any) => {
        return $$createType3($result);
    });
}

export function GetResourceMetrics(clusterCtx: string, gvr: string, $namespace: string, name: string, rangeMinutes: number): $CancellablePromise<metrics$0.MetricsResponse | null> {
    return $Call.ByID(90947346, clusterCtx, gvr, $namespace, name, rangeMinutes).then(($result: any) => {
        return $$createType5($result);
    });
}

export function RedetectSources(clusterCtx: string): $CancellablePromise<metrics$0.MetricsCapability | null> {
    return $Call.ByID(169399461, clusterCtx).then(($result: any) => {
        return $$createType6($result);
    });
}

export function SetPrometheusEndpoint(clusterCtx: string, url: string): $CancellablePromise<void> {
    return $Call.ByID(1645142504, clusterCtx, url);
}

// Private type creation functions
const $$createType0 = metrics$0.MetricsCapability.createFrom;
const $$createType1 = metrics$0.MetricResult.createFrom;
const $$createType2 = $Create.Array($$createType1);
const $$createType3 = $Create.Map($Create.Any, $$createType2);
const $$createType4 = metrics$0.MetricsResponse.createFrom;
const $$createType5 = $Create.Nullable($$createType4);
const $$createType6 = $Create.Nullable($$createType0);
