// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as cluster$0 from "../cluster/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as config$0 from "../config/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as time$0 from "../../../../../time/models.js";

export enum CapabilityState {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    CapabilityAvailable = "available",
    CapabilityUnavailable = "unavailable",
    CapabilityUnknown = "unknown",
};

export class ClusterInfo {
    "context": cluster$0.KubeContext;
    "serverUrl": string;
    "metricsServer": CapabilityState;
    "prometheusUrl": string;
    "prometheusSource": string;

    /** Creates a new ClusterInfo instance. */
    constructor($$source: Partial<ClusterInfo> = {}) {
        if (!("context" in $$source)) {
            this["context"] = (new cluster$0.KubeContext());
        }
        if (!("serverUrl" in $$source)) {
            this["serverUrl"] = "";
        }
        if (!("metricsServer" in $$source)) {
            this["metricsServer"] = CapabilityState.$zero;
        }
        if (!("prometheusUrl" in $$source)) {
            this["prometheusUrl"] = "";
        }
        if (!("prometheusSource" in $$source)) {
            this["prometheusSource"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ClusterInfo instance from a string or object.
     */
    static createFrom($$source: any = {}): ClusterInfo {
        const $$createField0_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("context" in $$parsedSource) {
            $$parsedSource["context"] = $$createField0_0($$parsedSource["context"]);
        }
        return new ClusterInfo($$parsedSource as Partial<ClusterInfo>);
    }
}

export class HelmPermissions {
    "canRollback": boolean;
    "canUninstall": boolean;
    "canTest": boolean;
    "canForceDelete": boolean;

    /** Creates a new HelmPermissions instance. */
    constructor($$source: Partial<HelmPermissions> = {}) {
        if (!("canRollback" in $$source)) {
            this["canRollback"] = false;
        }
        if (!("canUninstall" in $$source)) {
            this["canUninstall"] = false;
        }
        if (!("canTest" in $$source)) {
            this["canTest"] = false;
        }
        if (!("canForceDelete" in $$source)) {
            this["canForceDelete"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new HelmPermissions instance from a string or object.
     */
    static createFrom($$source: any = {}): HelmPermissions {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new HelmPermissions($$parsedSource as Partial<HelmPermissions>);
    }
}

export class HelmRollbackOpts {
    "wait": boolean;
    "timeout": number;
    "disableHooks": boolean;

    /** Creates a new HelmRollbackOpts instance. */
    constructor($$source: Partial<HelmRollbackOpts> = {}) {
        if (!("wait" in $$source)) {
            this["wait"] = false;
        }
        if (!("timeout" in $$source)) {
            this["timeout"] = 0;
        }
        if (!("disableHooks" in $$source)) {
            this["disableHooks"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new HelmRollbackOpts instance from a string or object.
     */
    static createFrom($$source: any = {}): HelmRollbackOpts {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new HelmRollbackOpts($$parsedSource as Partial<HelmRollbackOpts>);
    }
}

export class HelmTestOpts {
    "timeout": number;
    "filters"?: string[];

    /** Creates a new HelmTestOpts instance. */
    constructor($$source: Partial<HelmTestOpts> = {}) {
        if (!("timeout" in $$source)) {
            this["timeout"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new HelmTestOpts instance from a string or object.
     */
    static createFrom($$source: any = {}): HelmTestOpts {
        const $$createField1_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("filters" in $$parsedSource) {
            $$parsedSource["filters"] = $$createField1_0($$parsedSource["filters"]);
        }
        return new HelmTestOpts($$parsedSource as Partial<HelmTestOpts>);
    }
}

export class HelmUninstallOpts {
    "wait": boolean;
    "timeout": number;
    "disableHooks": boolean;
    "keepHistory": boolean;

    /** Creates a new HelmUninstallOpts instance. */
    constructor($$source: Partial<HelmUninstallOpts> = {}) {
        if (!("wait" in $$source)) {
            this["wait"] = false;
        }
        if (!("timeout" in $$source)) {
            this["timeout"] = 0;
        }
        if (!("disableHooks" in $$source)) {
            this["disableHooks"] = false;
        }
        if (!("keepHistory" in $$source)) {
            this["keepHistory"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new HelmUninstallOpts instance from a string or object.
     */
    static createFrom($$source: any = {}): HelmUninstallOpts {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new HelmUninstallOpts($$parsedSource as Partial<HelmUninstallOpts>);
    }
}

export class ListResult {
    "items": { [_ in string]?: any }[];
    "resourceVersion": string;

    /** Creates a new ListResult instance. */
    constructor($$source: Partial<ListResult> = {}) {
        if (!("items" in $$source)) {
            this["items"] = [];
        }
        if (!("resourceVersion" in $$source)) {
            this["resourceVersion"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ListResult instance from a string or object.
     */
    static createFrom($$source: any = {}): ListResult {
        const $$createField0_0 = $$createType3;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("items" in $$parsedSource) {
            $$parsedSource["items"] = $$createField0_0($$parsedSource["items"]);
        }
        return new ListResult($$parsedSource as Partial<ListResult>);
    }
}

export class ManagedPodDTO {
    "id": string;
    "contextName": string;
    "namespace": string;
    "podName": string;
    "pvcName": string;
    "createdAt": time$0.Time;
    "sessionUuid": string;
    "terminalTabId": string;

    /** Creates a new ManagedPodDTO instance. */
    constructor($$source: Partial<ManagedPodDTO> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("contextName" in $$source)) {
            this["contextName"] = "";
        }
        if (!("namespace" in $$source)) {
            this["namespace"] = "";
        }
        if (!("podName" in $$source)) {
            this["podName"] = "";
        }
        if (!("pvcName" in $$source)) {
            this["pvcName"] = "";
        }
        if (!("createdAt" in $$source)) {
            this["createdAt"] = null;
        }
        if (!("sessionUuid" in $$source)) {
            this["sessionUuid"] = "";
        }
        if (!("terminalTabId" in $$source)) {
            this["terminalTabId"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ManagedPodDTO instance from a string or object.
     */
    static createFrom($$source: any = {}): ManagedPodDTO {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ManagedPodDTO($$parsedSource as Partial<ManagedPodDTO>);
    }
}

export class OrphanPodDTO {
    "contextName": string;
    "namespace": string;
    "podName": string;
    "pvcName": string;
    "createdAt": time$0.Time;
    "sessionUuid": string;

    /** Creates a new OrphanPodDTO instance. */
    constructor($$source: Partial<OrphanPodDTO> = {}) {
        if (!("contextName" in $$source)) {
            this["contextName"] = "";
        }
        if (!("namespace" in $$source)) {
            this["namespace"] = "";
        }
        if (!("podName" in $$source)) {
            this["podName"] = "";
        }
        if (!("pvcName" in $$source)) {
            this["pvcName"] = "";
        }
        if (!("createdAt" in $$source)) {
            this["createdAt"] = null;
        }
        if (!("sessionUuid" in $$source)) {
            this["sessionUuid"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new OrphanPodDTO instance from a string or object.
     */
    static createFrom($$source: any = {}): OrphanPodDTO {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new OrphanPodDTO($$parsedSource as Partial<OrphanPodDTO>);
    }
}

export class RolloutRevision {
    "revision": number;
    "name": string;
    "labels"?: { [_ in string]?: any };

    /** Creates a new RolloutRevision instance. */
    constructor($$source: Partial<RolloutRevision> = {}) {
        if (!("revision" in $$source)) {
            this["revision"] = 0;
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new RolloutRevision instance from a string or object.
     */
    static createFrom($$source: any = {}): RolloutRevision {
        const $$createField2_0 = $$createType2;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("labels" in $$parsedSource) {
            $$parsedSource["labels"] = $$createField2_0($$parsedSource["labels"]);
        }
        return new RolloutRevision($$parsedSource as Partial<RolloutRevision>);
    }
}

export class SpawnOverridesDTO {
    "image"?: string | null;
    "mountPath"?: string | null;
    "readOnly"?: boolean | null;
    "activeDeadlineSeconds"?: number | null;
    "resources"?: config$0.ResourceReqs | null;
    "nodeSelector"?: { [_ in string]?: string };
    "tolerations"?: { [_ in string]?: any }[];

    /** Creates a new SpawnOverridesDTO instance. */
    constructor($$source: Partial<SpawnOverridesDTO> = {}) {

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SpawnOverridesDTO instance from a string or object.
     */
    static createFrom($$source: any = {}): SpawnOverridesDTO {
        const $$createField4_0 = $$createType5;
        const $$createField5_0 = $$createType6;
        const $$createField6_0 = $$createType3;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("resources" in $$parsedSource) {
            $$parsedSource["resources"] = $$createField4_0($$parsedSource["resources"]);
        }
        if ("nodeSelector" in $$parsedSource) {
            $$parsedSource["nodeSelector"] = $$createField5_0($$parsedSource["nodeSelector"]);
        }
        if ("tolerations" in $$parsedSource) {
            $$parsedSource["tolerations"] = $$createField6_0($$parsedSource["tolerations"]);
        }
        return new SpawnOverridesDTO($$parsedSource as Partial<SpawnOverridesDTO>);
    }
}

export class SpawnRequestDTO {
    "contextName": string;
    "namespace": string;
    "pvcName": string;
    "overrides"?: SpawnOverridesDTO | null;

    /** Creates a new SpawnRequestDTO instance. */
    constructor($$source: Partial<SpawnRequestDTO> = {}) {
        if (!("contextName" in $$source)) {
            this["contextName"] = "";
        }
        if (!("namespace" in $$source)) {
            this["namespace"] = "";
        }
        if (!("pvcName" in $$source)) {
            this["pvcName"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SpawnRequestDTO instance from a string or object.
     */
    static createFrom($$source: any = {}): SpawnRequestDTO {
        const $$createField3_0 = $$createType8;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("overrides" in $$parsedSource) {
            $$parsedSource["overrides"] = $$createField3_0($$parsedSource["overrides"]);
        }
        return new SpawnRequestDTO($$parsedSource as Partial<SpawnRequestDTO>);
    }
}

export class SpawnResult {
    "id": string;
    "namespace": string;
    "podName": string;

    /** Creates a new SpawnResult instance. */
    constructor($$source: Partial<SpawnResult> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("namespace" in $$source)) {
            this["namespace"] = "";
        }
        if (!("podName" in $$source)) {
            this["podName"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SpawnResult instance from a string or object.
     */
    static createFrom($$source: any = {}): SpawnResult {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SpawnResult($$parsedSource as Partial<SpawnResult>);
    }
}

// Private type creation functions
const $$createType0 = cluster$0.KubeContext.createFrom;
const $$createType1 = $Create.Array($Create.Any);
const $$createType2 = $Create.Map($Create.Any, $Create.Any);
const $$createType3 = $Create.Array($$createType2);
const $$createType4 = config$0.ResourceReqs.createFrom;
const $$createType5 = $Create.Nullable($$createType4);
const $$createType6 = $Create.Map($Create.Any, $Create.Any);
const $$createType7 = SpawnOverridesDTO.createFrom;
const $$createType8 = $Create.Nullable($$createType7);
