// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as plugin$0 from "../plugin/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as resource$0 from "../resource/models.js";

/**
 * AddInsecureRegistry appends host to the InsecureRegistries config list (no-op if already present).
 */
export function AddInsecureRegistry(host: string): $CancellablePromise<void> {
    return $Call.ByID(2550531315, host);
}

/**
 * DeletePluginStorageKey deletes a storage key for the named plugin.
 */
export function DeletePluginStorageKey(pluginName: string, key: string): $CancellablePromise<void> {
    return $Call.ByID(2741694887, pluginName, key);
}

/**
 * DisablePlugin deactivates a plugin without removing its registry entry.
 */
export function DisablePlugin(name: string): $CancellablePromise<void> {
    return $Call.ByID(2827133906, name);
}

/**
 * EmitClusterEvent notifies all active plugins with events permission about a cluster event.
 * Also emits a Wails "plugin:event" event so frontend plugin components can subscribe.
 */
export function EmitClusterEvent(eventName: string, payload: string): $CancellablePromise<void> {
    return $Call.ByID(2846539646, eventName, payload);
}

/**
 * EnablePlugin reloads a disabled plugin's runtime and re-registers its extension points.
 */
export function EnablePlugin(name: string): $CancellablePromise<void> {
    return $Call.ByID(3372152903, name);
}

export function GetPluginCommands(): $CancellablePromise<plugin$0.CommandEntry[]> {
    return $Call.ByID(2652726328).then(($result: any) => {
        return $$createType1($result);
    });
}

export function GetPluginContextMenuItems(gvr: string): $CancellablePromise<plugin$0.ContextMenuEntry[]> {
    return $Call.ByID(52700694, gvr).then(($result: any) => {
        return $$createType3($result);
    });
}

export function GetPluginDescriptors(): $CancellablePromise<(resource$0.Descriptor | null)[]> {
    return $Call.ByID(708743124).then(($result: any) => {
        return $$createType6($result);
    });
}

export function GetPluginDetailTabs(): $CancellablePromise<plugin$0.DetailTabEntry[]> {
    return $Call.ByID(1861103043).then(($result: any) => {
        return $$createType8($result);
    });
}

export function GetPluginHeaderWidgets(): $CancellablePromise<plugin$0.HeaderWidgetEntry[]> {
    return $Call.ByID(1768483840).then(($result: any) => {
        return $$createType10($result);
    });
}

export function GetPluginListColumns(gvr: string): $CancellablePromise<plugin$0.ListColumnEntry[]> {
    return $Call.ByID(2256052701, gvr).then(($result: any) => {
        return $$createType12($result);
    });
}

export function GetPluginMetricQueries(gvr: string): $CancellablePromise<plugin$0.MetricQueryEntry[]> {
    return $Call.ByID(1061603298, gvr).then(($result: any) => {
        return $$createType14($result);
    });
}

export function GetPluginOverviewFields(gvr: string): $CancellablePromise<plugin$0.OverviewFieldEntry[]> {
    return $Call.ByID(3013906384, gvr).then(($result: any) => {
        return $$createType16($result);
    });
}

export function GetPluginSettings(name: string): $CancellablePromise<string> {
    return $Call.ByID(2508857967, name);
}

export function GetPluginSettingsSchema(name: string): $CancellablePromise<string> {
    return $Call.ByID(281772880, name);
}

export function GetPluginSidebarEntries(): $CancellablePromise<plugin$0.SidebarEntry[]> {
    return $Call.ByID(3696952998).then(($result: any) => {
        return $$createType18($result);
    });
}

export function GetPluginStatusBarWidgets(): $CancellablePromise<plugin$0.StatusBarEntry[]> {
    return $Call.ByID(2691181182).then(($result: any) => {
        return $$createType20($result);
    });
}

/**
 * GetPluginStorageKey returns a storage value for the named plugin.
 */
export function GetPluginStorageKey(pluginName: string, key: string): $CancellablePromise<string> {
    return $Call.ByID(3107711926, pluginName, key);
}

/**
 * InstallPlugin installs a plugin from an OCI reference (oci://...), a directory path,
 * or an OCI archive (.oci.tar / .oci.tar.gz). After installation, loads the plugin and
 * emits plugins:loaded.
 */
export function InstallPlugin(path: string): $CancellablePromise<void> {
    return $Call.ByID(45558949, path);
}

/**
 * InvokeCommand dispatches a plugin command asynchronously.
 * Returns immediately; errors are emitted as plugin:error events.
 */
export function InvokeCommand(pluginName: string, commandID: string): $CancellablePromise<void> {
    return $Call.ByID(2591964872, pluginName, commandID);
}

/**
 * ListPluginStorageKeys returns all storage keys for the named plugin.
 */
export function ListPluginStorageKeys(pluginName: string): $CancellablePromise<string[]> {
    return $Call.ByID(246306153, pluginName).then(($result: any) => {
        return $$createType21($result);
    });
}

export function ListPlugins(): $CancellablePromise<plugin$0.PluginInfo[]> {
    return $Call.ByID(2936986561).then(($result: any) => {
        return $$createType23($result);
    });
}

/**
 * PackPlugin packs a plugin directory into an OCI tar.gz archive.
 * Returns the path to the generated archive.
 */
export function PackPlugin(pluginDir: string): $CancellablePromise<string> {
    return $Call.ByID(1780293953, pluginDir);
}

/**
 * ReloadPlugin performs a full unload-then-reload cycle for the named plugin.
 * Called by the PluginWatcher on file changes.
 */
export function ReloadPlugin(name: string): $CancellablePromise<void> {
    return $Call.ByID(2066653501, name);
}

/**
 * ReloadPluginManual is the Wails-bound version of ReloadPlugin.
 */
export function ReloadPluginManual(name: string): $CancellablePromise<void> {
    return $Call.ByID(1045275339, name);
}

/**
 * SaveRegistryCredentials persists credentials for an OCI registry host to ~/.docker/config.json.
 */
export function SaveRegistryCredentials(host: string, username: string, password: string): $CancellablePromise<void> {
    return $Call.ByID(1007465601, host, username, password);
}

export function SetPluginSettings(name: string, settingsJSON: string): $CancellablePromise<void> {
    return $Call.ByID(2550739915, name, settingsJSON);
}

/**
 * SetPluginStorageKey sets a storage value for the named plugin.
 */
export function SetPluginStorageKey(pluginName: string, key: string, value: string): $CancellablePromise<void> {
    return $Call.ByID(2619222610, pluginName, key, value);
}

/**
 * UninstallPlugin removes the plugin directory and all associated data.
 */
export function UninstallPlugin(name: string): $CancellablePromise<void> {
    return $Call.ByID(2836258476, name);
}

// Private type creation functions
const $$createType0 = plugin$0.CommandEntry.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = plugin$0.ContextMenuEntry.createFrom;
const $$createType3 = $Create.Array($$createType2);
const $$createType4 = resource$0.Descriptor.createFrom;
const $$createType5 = $Create.Nullable($$createType4);
const $$createType6 = $Create.Array($$createType5);
const $$createType7 = plugin$0.DetailTabEntry.createFrom;
const $$createType8 = $Create.Array($$createType7);
const $$createType9 = plugin$0.HeaderWidgetEntry.createFrom;
const $$createType10 = $Create.Array($$createType9);
const $$createType11 = plugin$0.ListColumnEntry.createFrom;
const $$createType12 = $Create.Array($$createType11);
const $$createType13 = plugin$0.MetricQueryEntry.createFrom;
const $$createType14 = $Create.Array($$createType13);
const $$createType15 = plugin$0.OverviewFieldEntry.createFrom;
const $$createType16 = $Create.Array($$createType15);
const $$createType17 = plugin$0.SidebarEntry.createFrom;
const $$createType18 = $Create.Array($$createType17);
const $$createType19 = plugin$0.StatusBarEntry.createFrom;
const $$createType20 = $Create.Array($$createType19);
const $$createType21 = $Create.Array($Create.Any);
const $$createType22 = plugin$0.PluginInfo.createFrom;
const $$createType23 = $Create.Array($$createType22);
