// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as config$0 from "../config/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as portforward$0 from "../portforward/models.js";

/**
 * ConnectSavedForward starts a saved forward using its existing ID so it
 * doesn't create a duplicate saved entry.
 */
export function ConnectSavedForward(ctxName: string, savedID: string): $CancellablePromise<portforward$0.ForwardSpec> {
    return $Call.ByID(646437684, ctxName, savedID).then(($result: any) => {
        return $$createType0($result);
    });
}

export function ListForwards(contextName: string): $CancellablePromise<portforward$0.ForwardSpec[]> {
    return $Call.ByID(4274792300, contextName).then(($result: any) => {
        return $$createType1($result);
    });
}

export function ListSavedPortForwards(ctxName: string): $CancellablePromise<config$0.SavedPortForward[]> {
    return $Call.ByID(2424660924, ctxName).then(($result: any) => {
        return $$createType3($result);
    });
}

export function RemoveSavedPortForward(ctxName: string, id: string): $CancellablePromise<void> {
    return $Call.ByID(1339133687, ctxName, id);
}

export function SavePortForward(ctxName: string, fwd: config$0.SavedPortForward): $CancellablePromise<void> {
    return $Call.ByID(334273145, ctxName, fwd);
}

export function SetPortForwardEnabled(ctxName: string, id: string, enabled: boolean): $CancellablePromise<void> {
    return $Call.ByID(1617244075, ctxName, id, enabled);
}

export function StartForward(contextName: string, $namespace: string, targetKind: portforward$0.TargetKind, targetName: string, targetGVR: string, localPort: number, remotePort: number): $CancellablePromise<portforward$0.ForwardSpec> {
    return $Call.ByID(2691853059, contextName, $namespace, targetKind, targetName, targetGVR, localPort, remotePort).then(($result: any) => {
        return $$createType0($result);
    });
}

export function StopForward(forwardID: string): $CancellablePromise<void> {
    return $Call.ByID(465318475, forwardID);
}

// Private type creation functions
const $$createType0 = portforward$0.ForwardSpec.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = config$0.SavedPortForward.createFrom;
const $$createType3 = $Create.Array($$createType2);
