// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as cluster$0 from "../cluster/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as resource$0 from "../resource/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as watcher$0 from "../watcher/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function ApplyManifest(contextName: string, yamlContent: string): $CancellablePromise<resource$0.ApplyResult[]> {
    return $Call.ByID(1808732929, contextName, yamlContent).then(($result: any) => {
        return $$createType1($result);
    });
}

export function CreateResource(contextName: string, gvr: string, $namespace: string, obj: { [_ in string]?: any }): $CancellablePromise<{ [_ in string]?: any }> {
    return $Call.ByID(1901610632, contextName, gvr, $namespace, obj).then(($result: any) => {
        return $$createType2($result);
    });
}

export function DeleteJobCascade(contextName: string, $namespace: string, name: string): $CancellablePromise<void> {
    return $Call.ByID(2160112924, contextName, $namespace, name);
}

export function DeleteJobOrphan(contextName: string, $namespace: string, name: string): $CancellablePromise<void> {
    return $Call.ByID(762631980, contextName, $namespace, name);
}

export function DeleteResource(contextName: string, gvr: string, $namespace: string, name: string): $CancellablePromise<void> {
    return $Call.ByID(1205855719, contextName, gvr, $namespace, name);
}

export function Engine(): $CancellablePromise<resource$0.ResourceEngine | null> {
    return $Call.ByID(2725305666).then(($result: any) => {
        return $$createType4($result);
    });
}

export function EnricherRegistry(): $CancellablePromise<resource$0.EnricherRegistry | null> {
    return $Call.ByID(2852732061).then(($result: any) => {
        return $$createType6($result);
    });
}

export function ExpandPVC(contextName: string, $namespace: string, name: string, newSize: string): $CancellablePromise<void> {
    return $Call.ByID(1652489051, contextName, $namespace, name, newSize);
}

export function ForceDeleteResource(contextName: string, gvr: string, $namespace: string, name: string): $CancellablePromise<void> {
    return $Call.ByID(1634363412, contextName, gvr, $namespace, name);
}

export function GetAllTemplateGVRs(contextName: string): $CancellablePromise<string[]> {
    return $Call.ByID(1012417887, contextName).then(($result: any) => {
        return $$createType7($result);
    });
}

export function GetDescriptors(): $CancellablePromise<(resource$0.Descriptor | null)[]> {
    return $Call.ByID(2292983530).then(($result: any) => {
        return $$createType10($result);
    });
}

export function GetEvents(contextName: string, $namespace: string, uid: string): $CancellablePromise<{ [_ in string]?: any }[]> {
    return $Call.ByID(3708386421, contextName, $namespace, uid).then(($result: any) => {
        return $$createType11($result);
    });
}

export function GetResource(contextName: string, gvr: string, $namespace: string, name: string): $CancellablePromise<{ [_ in string]?: any }> {
    return $Call.ByID(135959152, contextName, gvr, $namespace, name).then(($result: any) => {
        return $$createType2($result);
    });
}

export function GetRolloutHistory(contextName: string, gvr: string, $namespace: string, name: string): $CancellablePromise<$models.RolloutRevision[]> {
    return $Call.ByID(2359955171, contextName, gvr, $namespace, name).then(($result: any) => {
        return $$createType13($result);
    });
}

export function GetTemplates(contextName: string, gvr: string): $CancellablePromise<resource$0.Template[]> {
    return $Call.ByID(1548246975, contextName, gvr).then(($result: any) => {
        return $$createType15($result);
    });
}

export function ListAPIResources(contextName: string): $CancellablePromise<cluster$0.APIResource[]> {
    return $Call.ByID(1259308621, contextName).then(($result: any) => {
        return $$createType17($result);
    });
}

export function ListResources(contextName: string, gvr: string, $namespace: string): $CancellablePromise<{ [_ in string]?: any }[]> {
    return $Call.ByID(3351008733, contextName, gvr, $namespace).then(($result: any) => {
        return $$createType11($result);
    });
}

/**
 * ListResourcesWithVersion returns list items along with the list's ResourceVersion
 * so the caller can seed a subsequent watch without triggering a synthetic ADDED replay.
 */
export function ListResourcesWithVersion(contextName: string, gvr: string, $namespace: string): $CancellablePromise<$models.ListResult | null> {
    return $Call.ByID(595597419, contextName, gvr, $namespace).then(($result: any) => {
        return $$createType19($result);
    });
}

export function PauseRollout(contextName: string, $namespace: string, name: string): $CancellablePromise<void> {
    return $Call.ByID(1279088551, contextName, $namespace, name);
}

export function Registry(): $CancellablePromise<resource$0.Registry | null> {
    return $Call.ByID(3098448631).then(($result: any) => {
        return $$createType21($result);
    });
}

export function RestartResource(contextName: string, gvr: string, $namespace: string, name: string): $CancellablePromise<void> {
    return $Call.ByID(1778604759, contextName, gvr, $namespace, name);
}

export function ResumeCronJob(contextName: string, $namespace: string, name: string): $CancellablePromise<void> {
    return $Call.ByID(3937380918, contextName, $namespace, name);
}

export function ResumeRollout(contextName: string, $namespace: string, name: string): $CancellablePromise<void> {
    return $Call.ByID(3072590784, contextName, $namespace, name);
}

export function RollbackToRevision(contextName: string, gvr: string, $namespace: string, name: string, revision: number): $CancellablePromise<void> {
    return $Call.ByID(61840640, contextName, gvr, $namespace, name, revision);
}

export function ScaleResource(contextName: string, gvr: string, $namespace: string, name: string, replicas: number): $CancellablePromise<void> {
    return $Call.ByID(1670858778, contextName, gvr, $namespace, name, replicas);
}

export function StartWatch(contextName: string, gvr: string, $namespace: string, resourceVersion: string): $CancellablePromise<void> {
    return $Call.ByID(3194488095, contextName, gvr, $namespace, resourceVersion);
}

export function StopWatch(contextName: string, gvr: string, $namespace: string): $CancellablePromise<void> {
    return $Call.ByID(1152083571, contextName, gvr, $namespace);
}

export function SuspendCronJob(contextName: string, $namespace: string, name: string): $CancellablePromise<void> {
    return $Call.ByID(541678507, contextName, $namespace, name);
}

export function TriggerCronJob(contextName: string, $namespace: string, name: string): $CancellablePromise<void> {
    return $Call.ByID(2347619787, contextName, $namespace, name);
}

export function UpdateResource(contextName: string, gvr: string, $namespace: string, obj: { [_ in string]?: any }): $CancellablePromise<{ [_ in string]?: any }> {
    return $Call.ByID(2032718897, contextName, gvr, $namespace, obj).then(($result: any) => {
        return $$createType2($result);
    });
}

export function WatchMgr(): $CancellablePromise<watcher$0.WatchManager | null> {
    return $Call.ByID(1932566071).then(($result: any) => {
        return $$createType23($result);
    });
}

// Private type creation functions
const $$createType0 = resource$0.ApplyResult.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = $Create.Map($Create.Any, $Create.Any);
const $$createType3 = resource$0.ResourceEngine.createFrom;
const $$createType4 = $Create.Nullable($$createType3);
const $$createType5 = resource$0.EnricherRegistry.createFrom;
const $$createType6 = $Create.Nullable($$createType5);
const $$createType7 = $Create.Array($Create.Any);
const $$createType8 = resource$0.Descriptor.createFrom;
const $$createType9 = $Create.Nullable($$createType8);
const $$createType10 = $Create.Array($$createType9);
const $$createType11 = $Create.Array($$createType2);
const $$createType12 = $models.RolloutRevision.createFrom;
const $$createType13 = $Create.Array($$createType12);
const $$createType14 = resource$0.Template.createFrom;
const $$createType15 = $Create.Array($$createType14);
const $$createType16 = cluster$0.APIResource.createFrom;
const $$createType17 = $Create.Array($$createType16);
const $$createType18 = $models.ListResult.createFrom;
const $$createType19 = $Create.Nullable($$createType18);
const $$createType20 = resource$0.Registry.createFrom;
const $$createType21 = $Create.Nullable($$createType20);
const $$createType22 = watcher$0.WatchManager.createFrom;
const $$createType23 = $Create.Nullable($$createType22);
