// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function AttachTab(id: string, tabID: string): $CancellablePromise<void> {
    return $Call.ByID(3734750756, id, tabID);
}

/**
 * CleanupOrphans deletes all pvc-browser pods in the given context that are
 * not owned by the current session.
 */
export function CleanupOrphans(contextName: string): $CancellablePromise<void> {
    return $Call.ByID(586032643, contextName);
}

export function ListManaged(contextName: string): $CancellablePromise<$models.ManagedPodDTO[]> {
    return $Call.ByID(3272821081, contextName).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * Replace stops the pod referenced by id (if any) and spawns a new one.
 * Used when the user changes overrides for an already-attached browser pod.
 */
export function Replace(id: string, req: $models.SpawnRequestDTO): $CancellablePromise<$models.SpawnResult> {
    return $Call.ByID(109702944, id, req).then(($result: any) => {
        return $$createType2($result);
    });
}

export function ScanOrphans(contextName: string): $CancellablePromise<$models.OrphanPodDTO[]> {
    return $Call.ByID(4284101324, contextName).then(($result: any) => {
        return $$createType4($result);
    });
}

export function Spawn(req: $models.SpawnRequestDTO): $CancellablePromise<$models.SpawnResult> {
    return $Call.ByID(819807927, req).then(($result: any) => {
        return $$createType2($result);
    });
}

export function Stop(id: string): $CancellablePromise<void> {
    return $Call.ByID(42006192, id);
}

/**
 * TriggerOrphanScan runs the scan and applies the OrphanCleanupOnStartup
 * dispatch (auto/prompt/ignore) synchronously, returning the orphan list for
 * prompt mode. For ignore or after-auto-cleanup it returns an empty slice.
 * Used by the frontend on-mount pull path to avoid races against the
 * OnClusterConnected event.
 */
export function TriggerOrphanScan(contextName: string): $CancellablePromise<$models.OrphanPodDTO[]> {
    return $Call.ByID(1082977015, contextName).then(($result: any) => {
        return $$createType4($result);
    });
}

// Private type creation functions
const $$createType0 = $models.ManagedPodDTO.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = $models.SpawnResult.createFrom;
const $$createType3 = $models.OrphanPodDTO.createFrom;
const $$createType4 = $Create.Array($$createType3);
