// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class StreamingConfig {
    "port": number;
    "token": string;

    /** Creates a new StreamingConfig instance. */
    constructor($$source: Partial<StreamingConfig> = {}) {
        if (!("port" in $$source)) {
            this["port"] = 0;
        }
        if (!("token" in $$source)) {
            this["token"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new StreamingConfig instance from a string or object.
     */
    static createFrom($$source: any = {}): StreamingConfig {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new StreamingConfig($$parsedSource as Partial<StreamingConfig>);
    }
}
