// @ts-nocheck
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as cluster$0 from "../cluster/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as config$0 from "../config/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as time$0 from "../../../../../time/models.js";

/**
 * @readonly
 * @enum {string}
 */
export const CapabilityState = {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero: "",

    CapabilityAvailable: "available",
    CapabilityUnavailable: "unavailable",
    CapabilityUnknown: "unknown",
};

export class ClusterInfo {
    /**
     * Creates a new ClusterInfo instance.
     * @param {Partial<ClusterInfo>} [$$source = {}] - The source object to create the ClusterInfo.
     */
    constructor($$source = {}) {
        if (!("context" in $$source)) {
            /**
             * @member
             * @type {cluster$0.KubeContext}
             */
            this["context"] = (new cluster$0.KubeContext());
        }
        if (!("serverUrl" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["serverUrl"] = "";
        }
        if (!("metricsServer" in $$source)) {
            /**
             * @member
             * @type {CapabilityState}
             */
            this["metricsServer"] = CapabilityState.$zero;
        }
        if (!("prometheusUrl" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["prometheusUrl"] = "";
        }
        if (!("prometheusSource" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["prometheusSource"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ClusterInfo instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ClusterInfo}
     */
    static createFrom($$source = {}) {
        const $$createField0_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("context" in $$parsedSource) {
            $$parsedSource["context"] = $$createField0_0($$parsedSource["context"]);
        }
        return new ClusterInfo(/** @type {Partial<ClusterInfo>} */($$parsedSource));
    }
}

export class HelmPermissions {
    /**
     * Creates a new HelmPermissions instance.
     * @param {Partial<HelmPermissions>} [$$source = {}] - The source object to create the HelmPermissions.
     */
    constructor($$source = {}) {
        if (!("canRollback" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["canRollback"] = false;
        }
        if (!("canUninstall" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["canUninstall"] = false;
        }
        if (!("canTest" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["canTest"] = false;
        }
        if (!("canForceDelete" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["canForceDelete"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new HelmPermissions instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {HelmPermissions}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new HelmPermissions(/** @type {Partial<HelmPermissions>} */($$parsedSource));
    }
}

export class HelmRollbackOpts {
    /**
     * Creates a new HelmRollbackOpts instance.
     * @param {Partial<HelmRollbackOpts>} [$$source = {}] - The source object to create the HelmRollbackOpts.
     */
    constructor($$source = {}) {
        if (!("wait" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["wait"] = false;
        }
        if (!("timeout" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["timeout"] = 0;
        }
        if (!("disableHooks" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["disableHooks"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new HelmRollbackOpts instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {HelmRollbackOpts}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new HelmRollbackOpts(/** @type {Partial<HelmRollbackOpts>} */($$parsedSource));
    }
}

export class HelmTestOpts {
    /**
     * Creates a new HelmTestOpts instance.
     * @param {Partial<HelmTestOpts>} [$$source = {}] - The source object to create the HelmTestOpts.
     */
    constructor($$source = {}) {
        if (!("timeout" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["timeout"] = 0;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string[] | undefined}
             */
            this["filters"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new HelmTestOpts instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {HelmTestOpts}
     */
    static createFrom($$source = {}) {
        const $$createField1_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("filters" in $$parsedSource) {
            $$parsedSource["filters"] = $$createField1_0($$parsedSource["filters"]);
        }
        return new HelmTestOpts(/** @type {Partial<HelmTestOpts>} */($$parsedSource));
    }
}

export class HelmUninstallOpts {
    /**
     * Creates a new HelmUninstallOpts instance.
     * @param {Partial<HelmUninstallOpts>} [$$source = {}] - The source object to create the HelmUninstallOpts.
     */
    constructor($$source = {}) {
        if (!("wait" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["wait"] = false;
        }
        if (!("timeout" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["timeout"] = 0;
        }
        if (!("disableHooks" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["disableHooks"] = false;
        }
        if (!("keepHistory" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["keepHistory"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new HelmUninstallOpts instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {HelmUninstallOpts}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new HelmUninstallOpts(/** @type {Partial<HelmUninstallOpts>} */($$parsedSource));
    }
}

export class ListResult {
    /**
     * Creates a new ListResult instance.
     * @param {Partial<ListResult>} [$$source = {}] - The source object to create the ListResult.
     */
    constructor($$source = {}) {
        if (!("items" in $$source)) {
            /**
             * @member
             * @type {{ [_ in string]?: any }[]}
             */
            this["items"] = [];
        }
        if (!("resourceVersion" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["resourceVersion"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ListResult instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ListResult}
     */
    static createFrom($$source = {}) {
        const $$createField0_0 = $$createType3;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("items" in $$parsedSource) {
            $$parsedSource["items"] = $$createField0_0($$parsedSource["items"]);
        }
        return new ListResult(/** @type {Partial<ListResult>} */($$parsedSource));
    }
}

export class ManagedPodDTO {
    /**
     * Creates a new ManagedPodDTO instance.
     * @param {Partial<ManagedPodDTO>} [$$source = {}] - The source object to create the ManagedPodDTO.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("contextName" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["contextName"] = "";
        }
        if (!("namespace" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["namespace"] = "";
        }
        if (!("podName" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["podName"] = "";
        }
        if (!("pvcName" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["pvcName"] = "";
        }
        if (!("createdAt" in $$source)) {
            /**
             * @member
             * @type {time$0.Time}
             */
            this["createdAt"] = null;
        }
        if (!("sessionUuid" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["sessionUuid"] = "";
        }
        if (!("terminalTabId" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["terminalTabId"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ManagedPodDTO instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ManagedPodDTO}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ManagedPodDTO(/** @type {Partial<ManagedPodDTO>} */($$parsedSource));
    }
}

export class OrphanPodDTO {
    /**
     * Creates a new OrphanPodDTO instance.
     * @param {Partial<OrphanPodDTO>} [$$source = {}] - The source object to create the OrphanPodDTO.
     */
    constructor($$source = {}) {
        if (!("contextName" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["contextName"] = "";
        }
        if (!("namespace" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["namespace"] = "";
        }
        if (!("podName" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["podName"] = "";
        }
        if (!("pvcName" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["pvcName"] = "";
        }
        if (!("createdAt" in $$source)) {
            /**
             * @member
             * @type {time$0.Time}
             */
            this["createdAt"] = null;
        }
        if (!("sessionUuid" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["sessionUuid"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new OrphanPodDTO instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {OrphanPodDTO}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new OrphanPodDTO(/** @type {Partial<OrphanPodDTO>} */($$parsedSource));
    }
}

export class RolloutRevision {
    /**
     * Creates a new RolloutRevision instance.
     * @param {Partial<RolloutRevision>} [$$source = {}] - The source object to create the RolloutRevision.
     */
    constructor($$source = {}) {
        if (!("revision" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["revision"] = 0;
        }
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {{ [_ in string]?: any } | undefined}
             */
            this["labels"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new RolloutRevision instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {RolloutRevision}
     */
    static createFrom($$source = {}) {
        const $$createField2_0 = $$createType2;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("labels" in $$parsedSource) {
            $$parsedSource["labels"] = $$createField2_0($$parsedSource["labels"]);
        }
        return new RolloutRevision(/** @type {Partial<RolloutRevision>} */($$parsedSource));
    }
}

export class SpawnOverridesDTO {
    /**
     * Creates a new SpawnOverridesDTO instance.
     * @param {Partial<SpawnOverridesDTO>} [$$source = {}] - The source object to create the SpawnOverridesDTO.
     */
    constructor($$source = {}) {
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | null | undefined}
             */
            this["image"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | null | undefined}
             */
            this["mountPath"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {boolean | null | undefined}
             */
            this["readOnly"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {number | null | undefined}
             */
            this["activeDeadlineSeconds"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {config$0.ResourceReqs | null | undefined}
             */
            this["resources"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {{ [_ in string]?: string } | undefined}
             */
            this["nodeSelector"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {{ [_ in string]?: any }[] | undefined}
             */
            this["tolerations"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SpawnOverridesDTO instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {SpawnOverridesDTO}
     */
    static createFrom($$source = {}) {
        const $$createField4_0 = $$createType5;
        const $$createField5_0 = $$createType6;
        const $$createField6_0 = $$createType3;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("resources" in $$parsedSource) {
            $$parsedSource["resources"] = $$createField4_0($$parsedSource["resources"]);
        }
        if ("nodeSelector" in $$parsedSource) {
            $$parsedSource["nodeSelector"] = $$createField5_0($$parsedSource["nodeSelector"]);
        }
        if ("tolerations" in $$parsedSource) {
            $$parsedSource["tolerations"] = $$createField6_0($$parsedSource["tolerations"]);
        }
        return new SpawnOverridesDTO(/** @type {Partial<SpawnOverridesDTO>} */($$parsedSource));
    }
}

export class SpawnRequestDTO {
    /**
     * Creates a new SpawnRequestDTO instance.
     * @param {Partial<SpawnRequestDTO>} [$$source = {}] - The source object to create the SpawnRequestDTO.
     */
    constructor($$source = {}) {
        if (!("contextName" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["contextName"] = "";
        }
        if (!("namespace" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["namespace"] = "";
        }
        if (!("pvcName" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["pvcName"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {SpawnOverridesDTO | null | undefined}
             */
            this["overrides"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SpawnRequestDTO instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {SpawnRequestDTO}
     */
    static createFrom($$source = {}) {
        const $$createField3_0 = $$createType8;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("overrides" in $$parsedSource) {
            $$parsedSource["overrides"] = $$createField3_0($$parsedSource["overrides"]);
        }
        return new SpawnRequestDTO(/** @type {Partial<SpawnRequestDTO>} */($$parsedSource));
    }
}

export class SpawnResult {
    /**
     * Creates a new SpawnResult instance.
     * @param {Partial<SpawnResult>} [$$source = {}] - The source object to create the SpawnResult.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("namespace" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["namespace"] = "";
        }
        if (!("podName" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["podName"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SpawnResult instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {SpawnResult}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SpawnResult(/** @type {Partial<SpawnResult>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = cluster$0.KubeContext.createFrom;
const $$createType1 = $Create.Array($Create.Any);
const $$createType2 = $Create.Map($Create.Any, $Create.Any);
const $$createType3 = $Create.Array($$createType2);
const $$createType4 = config$0.ResourceReqs.createFrom;
const $$createType5 = $Create.Nullable($$createType4);
const $$createType6 = $Create.Map($Create.Any, $Create.Any);
const $$createType7 = SpawnOverridesDTO.createFrom;
const $$createType8 = $Create.Nullable($$createType7);
